### ISSUE TITLE
Cada cuanto abren las inscripciones para el bootcamp de desarrollo web?

### ISSUE THREAD

**Issue by Sonstef** [Laboratoria/tech-support#100]
En este espacio puedes agregar el contexto necesario: texto, screenshots, etc.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es?utm_source=laboratoria_web&utm_campaign=footer_laboratoria-web&utm_medium=footer&_ga=2.204676880.1639442915.1696373153-964085431.1687795876`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
hola @Sonstef muchas gracias por contactarnos, esa información te la puede dar el equipo de admisiones, puedes consultarles  escribiendoles al siguiente email:  [postula@laboratoria.la](mailto:postula@laboratoria.la), ellos manejan la planificación de todas  las admisiones.
Que tengas buen día.
