### ISSUE TITLE
Puedo volver a aplicar?

### ISSUE THREAD

**Issue by KIT-KINI** [Laboratoria/tech-support#101]
Hola,

Apliqué al Bootcamp anterior pero tuve que salirme en la última etapa. Intento aplicar de nuevo pero no puedo porque me indica que ya tengo una solicitud enviada.

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/applications/207955`
**User Agent**: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36`
**Navigator Language**: `es-US`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @KIT-KINI , gracias por contactarte con nosotros, para cualquier consulta respecto al estado de tu postulación o información respecto a cómo volver a aplicar debes escribir al siguiente email: postula@laboratoria.la

Que tengas buen día.
