### ISSUE TITLE
[¿Cómo puedo cambiar mi foto de perfil?] Ayuda para poder cambiar foto de perfil

### ISSUE THREAD

**Issue by jlonuz** [Laboratoria/tech-support#102]
Hola! 
Necesito cambiar foto de perfil en mi cuenta, pero no se puede hacer aún. O desde dónde se puede cambiar? quizás la agarra desde otro lado, no sé. 
No es urgente lo sé, pero en mi caso, me gustaría poder poner una foto que me represente más. La actual es esta
![image](https://github.com/Laboratoria/tech-support/assets/20929382/63f1543e-98d8-4226-9f26-d8638b6c5d27)

Espero me puedan ayudar!
Muchas gracias por toda la motivación que le ponen al proyecto <3

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/account`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36`
**Navigator Language**: `es-US`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @jlonuz, muchas gracias por contactarte con nosotros, efectivamente la fotografía de tu perfil se toma desde tu Github. Asi que si quieres cambiar la fotografía debería cambiarlo en tu perfil de Github. 
Una vez que lo hagas deberías poder ver ya la fotografía cambiada, de no ser así  recuerda borrar el caché del navegador y volver a cargar la página de tu perfil en la plataforma de Laboratoria. 

Espero esto te sea de ayuda, ten un buen día.
P.D: Muchas gracias por tu mensaje de agradecimiento 👍🏼
