### ISSUE TITLE
[Bug] Problema de postulación a Desarrollo Web en Colombia

### ISSUE THREAD

**Issue by Kikariana** [Laboratoria/tech-support#103]
**Describe el problema**
Al momento de postularme al programa de Desarrollo Web y poner mi país de residencia Colombia me dice que no hay plazas disponibles y que diligencie un formulario, al ingresar al formulario dice diligencie si no nos encontramos en su país, pero si mencionan a Colombia. Entonces no me he podido postular

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a 'Desarrollo Web' 
2. Hacer click en 'postular'
3. Hacer scroll hacia abajo hasta '¿En qué país vives? Poner Colombia'
4. Ver error

**Comportamiento esperado**
Al poner Colombia, esperaba poder seguir postulándome

**Screenshots**
![image](https://github.com/Laboratoria/tech-support/assets/134741003/95fc5fa0-4022-4850-8c6b-1223e0ee1144)
![image](https://github.com/Laboratoria/tech-support/assets/134741003/94b1aaef-997d-44b4-bcf6-db7cac2e9664)
**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

**Comment by adolivaresl** [comment]
Hola @Kikariana, muchas gracias por contactarte con nosotros. Entendemos de dónde viene la confusión y nos disculpamos ante eso. Efectivamente, si bien operamos dentro de Colombia, en este momento, el único cohort disponible para postular no tiene plazas disponibles para personas en Colombia, Chile, México, etc. Solo está disponible para los siguientes países: Bolivia, Costa Rica, Ecuador, Panamá, Paraguay y Uruguay. Eso no quita que en el futuro existan nuevos cohorts con plazas para personas en Colombia.

Aún así, si quieres obtener más información al respecto, puedes escribir al siguiente correo electrónico: [postula@laboratoria.la](mailto:postula@laboratoria.la). 
Nuevamente lamentamos la confusión y agradecemos que lo hayas reportado. ¡Ten un buen día!
![image](https://github.com/Laboratoria/tech-support/assets/32287138/74a2ab5e-4b1c-4c29-ae56-64a74ade70ec)
