### ISSUE TITLE
[Bug] Error en editor de texto para código

### ISSUE THREAD

**Issue by Karenfonseca22** [Laboratoria/tech-support#104]
**Describe el problema**
Al realizar las pruebas del problema "cuenta de restaurante", no reconoce la función definida en el editor de texto para código

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir al ejercicio "cuenta de restaurante" para la prueba del bootcamp desarrollo web
2. Escribir un código donde se implemente la función restaurantBill
3. Darle clic al botón "ejecutar prueba"
4. Ver error, ya que no reconoce la función

**Comportamiento esperado**
Que reconozca las funciones debidamente, o me indique el tipo de error que estoy cometiendo, ya que no genera información

**Screenshots**
Se dejan dos pantallazos en donde se podrá ver que me aparece el mismo error, aunque tenga información diferente en el editor.
![image](https://github.com/Laboratoria/tech-support/assets/149629605/8ff5162f-df1d-47fe-9241-2bb0206c843e)
Se envía evidencia de que el ejercicio funciona, ejecutándolo en consola
![image](https://github.com/Laboratoria/tech-support/assets/149629605/cd76c55a-6a25-418c-9110-442657f9fb2b)

**Contexto adicional**
Es la primera prueba de la etapa 1, y la página ha estado abierta todo el día

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/applications/210339/challenges/restaurant-bill`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @Karenfonseca22, hay una línea importante al final del código que viene en el boilerplate pero que veo que no está en tu código. Éste  es **module.exports = restaurantBill;** esta línea de código es el que exporta tu código para que los test tomen tus lineas de código y lo verifiquen.
Espero esto ayude, que tengas buen día.
![image](https://github.com/Laboratoria/tech-support/assets/32287138/d6e10444-400e-4f5e-8c2a-74b03c1eacb8)
