### ISSUE TITLE
¿Cuándo se apertura las inscripciones de Bootcamp de desarrollo web para Perú?

### ISSUE THREAD

**Issue by lilianaboorj** [Laboratoria/tech-support#107]
![Captura de pantalla 2023-11-09 140824](https://github.com/Laboratoria/tech-support/assets/150384424/3fc5637f-af5e-4830-b961-c22d99ceccb0)

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es?utm_source=laboratoria_web&utm_campaign=hacemos_laboratoria-web&utm_medium=hacemos`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @lilianaboorj, gracias por contactarnos. Para recibir información sobre próximas plaza para Perú puedes escribir a este email:  [postula@laboratoria.la](mailto:postula@laboratoria.la)
que tengas buen día.
