### ISSUE TITLE
[Bug] Reemplaza este texto con el título

### ISSUE THREAD

**Issue by AngieMontenegroR** [Laboratoria/tech-support#108]
**Describe el problema**
Descripción clara y concisa de cuál es el problema.

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a '...'
2. Hacer click en '....'
3. Hacer scroll hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Descripción clara y concisa de qué esperabas que ocurriera.

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/account`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Buen día @AngieMontenegroR veo que has abierto un issue pero no has escrito nada. Cuéntanos si necesitas apoyo en algo.

**Comment by AngieMontenegroR** [comment]
Hola, buenos dias.
si, necesito ayuda; estaba haciendo mi proceso de inscripción para el bootcamp de diseño ux y el día 13 envié mi inscripción el prototipo de figma y el cuestionario, al entrar ayer a revisar me salió admisión cancelada. no se si tuve un error al momento de enviarlo, pero me preocupa que no quede bien mi inscripción, tengo muchas ganas de estudiar con ustedes y no quisiera perder esta oportunidad. ayer envié un correo a ***@***.*** y quedo en revisión el caso.

yo tengo el trabajo si es necesario lo envió nuevamente.
muchas gracias y espero poder seguir el proceso y estudiar con ustedes.
que tengas bonito día.

________________________________
De: Domi Olivares ***@***.***>
Enviado: miércoles, 15 de noviembre de 2023 7:23 a. m.
Para: Laboratoria/tech-support ***@***.***>
Cc: AngieMontenegroR ***@***.***>; Mention ***@***.***>
Asunto: Re: [Laboratoria/tech-support] [Bug] Reemplaza este texto con el título (Issue #108)


Buen día @AngieMontenegroR<https://github.com/AngieMontenegroR> veo que has abierto un issue pero no has escrito nada. Cuéntanos si necesitas apoyo en algo.

**Comment by adolivaresl** [comment]
@AngieMontenegroR, por lo que me cuentas entonces ya están revisando tu caso, así que debes seguir la comunicación con la persona a la que enviaste el correo y esperar a ver que te dicen.
Espero que todo salga bien.
Que tengas buen día tu también.
