### ISSUE TITLE
por que no puedo aplicar para el curso como desarrollladora web?

### ISSUE THREAD

**Issue by xochitlhg** [Laboratoria/tech-support#110]
hola, he intentado aplicar varias veces para el curso de desarrollo web y no obtengo ninguna respuesta

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

**Comment by ib-frida** [comment]
Hola Xochitl, por el momento estamos abiertas en países específicos, si no pasaste el filtro puede ser por esa razón. Estaremos abriendo convocatoria pronto:)
