### ISSUE TITLE
¿cuándo se abre bootcamp de desarrollo web en México? 

### ISSUE THREAD

**Issue by DChapadelBosque** [Laboratoria/tech-support#111]
Hola, ¿cuándo se abre bootcamp de desarrollo web en México?, intenté aplicar para el bootcamp, pero me dice que por el momento no esta disponible en México
Gracias

En este espacio puedes agregar el contexto necesario: texto, screenshots, etc.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/auth/signin`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by ib-frida** [comment]
Hola, por el momento no tenemos convocatorias en México:)
Pronto abriremos, puedes estar pendiente en nuestras redes.
