### ISSUE TITLE
[Bug] Substitua este texto pelo título

### ISSUE THREAD

**Issue by majubix** [Laboratoria/tech-support#112]
**Descreva o problema**
Descrição clara e concisa de qual é o problema.
Ao me candidatar ao bootcamp de Análise de Dados, não aparece o país "Brasil", mas o bootcamp atualmente só está disponível para quem mora aqui.
Sendo assim não é possivel concluir a inscrição.

**Para jogar**
Etapas para reproduzir o problema:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Descrição clara e concisa do que você esperava que acontecesse.
Deveria ter a opção "Brasil" já que o bootcamp só está disponível aqui

**Screenshots**
Se possível, adicione capturas de tela para ajudar a entender
o problema.
![Captura de tela 2024-01-22 231324](https://github.com/Laboratoria/tech-support/assets/106602446/2dc082a3-90eb-4b09-a0f5-a84599c9cca0)

## Entorno

**Location**: `https://bootcamp.laboratoria.la/pt/`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`
**Navigator Language**: `pt-BR`
**Selected Language**: `pt`

**Comment by adolivaresl** [comment]
Olá @majubix , tente inserir as primeiras letras do Brasil e a opção aparecerá.
