### ISSUE TITLE
[Bug] O site diz que só pode se candidatar quem morar no Brasil e não tem o Brasil pra selecionar como pais que mora. Meu filhooooo, acorde aí 

### ISSUE THREAD

**Issue by vickybispo** [Laboratoria/tech-support#113]
**Descreva o problema**
Descrição clara e concisa de qual é o problema.

**Para jogar**
Etapas para reproduzir o problema:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Descrição clara e concisa do que você esperava que acontecesse.

**Screenshots**
Se possível, adicione capturas de tela para ajudar a entender
o problema.

**Contexto adicional**
Adicione qualquer outra coisa que possa ajudar a entender o contexto em que
o problema ocorre.

**Alerta**
Lembre-se que este repositório é público, todos os problemas e conversas
relacionados são públicos e visíveis para todos.
Se você precisar compartilhar informações conosco em particular, NÃO faça isso por meio deste repositório,
Entraremos em contato com você para poder fornecer suporte por meio de um canal privado.

**Comment by adolivaresl** [comment]
Olá @vickybispo , você pode digitar as primeiras letras do Brasil no campo de entrada e a opção aparecerá para ser selecionada. Tenha um bom dia.
