### ISSUE TITLE
carga horária e pagamento

### ISSUE THREAD

**Issue by Lyohna** [Laboratoria/tech-support#114]
Ola na descrição do pagamento é após conseguir um emprego, gostaria de saber melhor como isso funciona.
E em relação a carga horária consta que 4 horas são aulas no Zoom e as outras 4 ? pra fechar o total informado de 8 horas?

**Comment by vale-vanessa** [comment]
Olá, tudo bem? Você pode escrever para **selecao@laboratoria.la**, por favor? Conseguiremos te ajudar por lá!
