### ISSUE TITLE
¿como usar el material de prueba?

### ISSUE THREAD

**Issue by andrecasdu** [Laboratoria/tech-support#115]
Hola, estoy haciendo las pruebas pero no entiendo, hay algun tutorial?

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://curriculum.laboratoria.la/es/`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`
**Navigator Language**: `es-US`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @andrecasdu, podrías darme más contexto para poder ayudarte? A qué bootcamp estas postulando y que parte del proceso no entiendes?

**Comment by andrecasdu** [comment]
![problemas](https://github.com/Laboratoria/tech-support/assets/159086964/222528df-4db1-492b-9e22-f27d29e92efa)
![thumbnail_IMG_2800](https://github.com/Laboratoria/tech-support/assets/159086964/64b44ce8-5fa5-419b-b287-b677623ae0b2)

Muchas gracias por responder. Me postule a desarrollo web y hay que realizar una serie de problemas, en el currículo, pero pues no se como ejecutar esto, ya que no se que tipo de códigos se utiliza, oh como agregar los códigos , quiero hacer todas las pruebas pero no llego a comprender los problemas. Ejemplo el cambio de moneda, que es un problema que ponen, que dan la plantilla, mas no dice como usar la plantilla, oh yo no lo entiendo. Necesito ayuda, ya que esto me interesa mucho pero quiero aprender. Gracias por la respuesta. Espero las imágenes que mande se puedan visualizar.

**Comment by adolivaresl** [comment]
Gracias por darme más contexto @andrecasdu, entiendo entonces que estas en la etapa de realizar los retos de código para poder enviar tu postulación al bootcamp de desarrollo web.

 Si ese es el caso el lugar desde donde debes realizar los retos **no es en la currícula**, si no que es en la misma página web desde donde estas postulando [https://bootcamp.laboratoria.la/es/](https://bootcamp.laboratoria.la/es/) 

1. Aquí cuando inicies sesión (con el email y contraseña con que creaste tu usuaria) le das clic a tu imagen de usuaria y te aparecerá un menú lateral. 
![paso_1](https://github.com/Laboratoria/tech-support/assets/32287138/ca11cb4d-aa41-401e-9e4d-d6c989f6043e)


2. Al seleccionar tu nombre e email te llevará a la vista de tu cuenta, que se vera algo como esto (los datos de esta foto son referenciales, no es la misma información que te mostrará a ti):
![image](https://github.com/Laboratoria/tech-support/assets/32287138/ed5757c4-afd1-499e-bae7-c56f7d3be8b9)

3. Al seleccionar sobre la caja que dice desarrollo web, te llevará a la vista donde estarán los retos del código que debes completar, es aquí desde donde debes desarrollar tu codigo:
![image](https://github.com/Laboratoria/tech-support/assets/32287138/9be1ae58-cdb9-4552-b23a-5f495d02b13b)

### Ahora como debes utilizar el editor de texto que está integrado en los retos:
Para desarrollar el reto debes escribir tu código en las secciones que salen con éste símbolo "/* ??? */" solo haces clic encima y ya puedes anotar lo que quieras, puedes borrarlo y colocar tu código.
![secciones-editar](https://github.com/Laboratoria/tech-support/assets/32287138/55f24a8c-a126-4541-80a4-61f937073467)


como puedes ver la sección verde es donde tu puedes escribir, solo preocúpate de no borrar la frase que está subrayada con rojo ya que es necesaria para que corran los test.
![editado](https://github.com/Laboratoria/tech-support/assets/32287138/ea75637a-03dd-4bdf-9a51-ba6ea0d2f927)

Si quieres ir probando si tu código está ok o no, debes apretar el botón de "ejecutar pruebas", deberas ir modificando tu código de acuerdo a lo que te vaya diciendo el resultado de los test: 
![image](https://github.com/Laboratoria/tech-support/assets/32287138/c6e58876-223b-45a6-bc0b-8220956a4a5a)
hasta que los test no pasen (queden de color verde) de ambos retos no podrás enviar tu postulación.

Espero haberte ayudado, que tengas buena tarde.

**Comment by andrecasdu** [comment]
Ahhhhh ok ya entendi. Mil gracias. otra pregunta, solo me puedo inscribir a este programa oh puedo inscribirme a otro de ustedes ?

**Comment by adolivaresl** [comment]
@andrecasdu puedes inscribirte a los que quieras, siempre cuando en el que estas ahora haya terminado su proceso de admisión. cuando el proceso de admisión de desarrollo web cierre, puedes postular a otro.
