### ISSUE TITLE
[Pregunta] Cómo puedo descargar el dataset para iniciar el taller?

### ISSUE THREAD

**Issue by CatheBta** [Laboratoria/tech-support#116]
Buenas tardes
Estoy tratando de descargar el dataset de cinemaster para iniciar el taller de la postulación ¿me pueden ayudar? por favor, dejo screenshot del problema 
![No Descarga el Datset google sheet Drive](https://github.com/Laboratoria/tech-support/assets/160442901/c2a34557-2f25-48fb-832d-be8a409d51dd)
 

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/data?utm_source=laboratoria_web&utm_campaign=data_analytics-laboratoria_web&utm_medium=proximos_bootcamps&_ga=2.165955710.1302854989.1708302457-1151430468.1705622848`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @CatheBta, puedes darme más detalles? el link lo obtuviste por medio de tu postulación? puedes contarme más del paso a paso hasta llegar al mensaje que nos has mostrado?
Tienes una cuenta de Gmail?

**Comment by CatheBta** [comment]
Buenos días 

Si señora el link lo obtuve por medio de mi postulación 

El paso a paso: ingresar a las instrucciones del taller e ingresar al link de descarga del dataset , al ingresar me dice descargar copia , pinchó ahí y me dice que no puede ser descargado 

Y si, tengo cuenta de Gmail

**Comment by adolivaresl** [comment]
@CatheBta este es el link que te abre para copiar?docs.google.com/spreadsheets/d/1EyjDS8yLtnmtY2zgRWDmeautxwnEVmns05c4LTpZTRs/copy?
y si revisas tu google Drive, no aparece la copia?

**Comment by CatheBta** [comment]
Bueno acabo de probar desde mi celular y acá si me deja abrir el archivo, con ese ya puedo empezar a trabajar si ?

**Comment by CatheBta** [comment]
Y te confirmo que el archivo ya me aparece en mi drive , muchas gracias por tu apoyo!

**Comment by adolivaresl** [comment]
Súper! me alegro que pudieras copiarlo! 
Éxito en tu postulación @CatheBta , que tengas buen día.

**Comment by CatheBta** [comment]
Hola buenos días 

Espero se encuentren bien, en relación a la consulta anterior, requiero apoyo ya que efectivamente el archivo está en mi Drive(antes no aparecía )pero no me deja editarlo para trabajar.

Dejo pantallazo 

Quedó muy atenta,
 gracias!![Screenshot_2024-02-21-10-56-49-124_com.whatsapp.jpg](https://github.com/Laboratoria/tech-support/assets/160442901/6c27885e-8fe8-47e7-97be-38e6460a54f0)
