### ISSUE TITLE
Cuándo abrirán postulaciones para el bootcamp de UX/UI en México este 2024?

### ISSUE THREAD

**Issue by AbrilKarely** [Laboratoria/tech-support#117]
Hola!
Cuándo abrirán postulaciones para el bootcamp de UX/UI en México este 2024?
Veo que se acaba de abrir un espacio pero México no aplica este año?
Saludos,

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by ib-frida** [comment]
Hola, por el momento no está abierta, pero será pronto:)
