### ISSUE TITLE
Hola buen dìa. Ya estoy realizando los retos correspondientes, pero sigo sin entender, el paso a paso, o sea como manejo las etiquetas, que va en cada etiqueta, si va dentro de las etiquetas, o sea como un ejemplo para realizar los retos. La verdad no,logro entenderlo, no me es claro como poner las etiquetas dentro de las etiquetas. No se si alguien me pueda ayudar con un ejmplo claro de la etiqueta, de como queda escrita . Tambien si me pueden ayudar con la plantilla, pues siento que borre ciertas cosas y ahora me desubique, y no se donde poner cada elemento que me piden. Gracias

### ISSUE THREAD

**Issue by andrecasdu** [Laboratoria/tech-support#118]
En este espacio puedes agregar el contexto necesario: texto, screenshots, etc.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/?utm_source=laboratoria_web&utm_medium=header&utm_campaign=header_laboratoria-web`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`
**Navigator Language**: `es-US`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @andrecasdu, dentro de cada reto vienen links a documentación que te servirá para desarrollar el reto, claramente puedes consultar  información por tu cuenta en internet (blogs, tutoriales, etc).

Te dejó como estaba la plantilla del reto de "Portafolio" en un inicio para que vayas comparando con lo que tienes y puedas volver a organizar tu código.

![image](https://github.com/Laboratoria/tech-support/assets/32287138/9c940821-022f-48be-8243-d2cbd9f5ecd9)
