### ISSUE TITLE
No me permite editar el archivo de dataset

### ISSUE THREAD

**Issue by CatheBta** [Laboratoria/tech-support#119]
Buenas noches 

Anteriormente me comunique porque el dataset no aparecía en mi Drive, ahora ya aparece pero no me deja copiar ni editar , no se si tiene que ver con que no tengo espacio en la cuenta Google, me podrías confirmar por favor , y en caso de ser esta la razón te pregunto, ¿puedo crear otra cuenta de Gmail? ¿debo actualizar mis datos en mi cuenta de Laborartoria? 
Adjunto pantallazos , muchas gracias!
![WhatsApp Image 2024-02-21 at 6 29 57 PM](https://github.com/Laboratoria/tech-support/assets/160442901/31d107f0-cebb-4708-931c-fea3b2adfcd7)
![WhatsApp Image 2024-02-21 at 7 06 09 PM](https://github.com/Laboratoria/tech-support/assets/160442901/c979e29e-942a-4fa9-a2d3-125cf992e6e3)

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/applications/219497/challenges/cine-master`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @CatheBta, no habría problema si realizas el reto desde otra cuenta de google, lo importante es que a la hora de compartirnos el link, este esté de manera pública para que podamos acceder sin tener que pedir permiso. Y si, efectivamente tu Drive está lleno y no te permitirá editar la copia del dataset para realizar el reto.
