### ISSUE TITLE
Ajuste texto "aviso" - pregunta ¿Tienes permiso para trabajar en el país donde vives?

### ISSUE THREAD

**Issue by JulianaFacciolla** [Laboratoria/tech-support#12]
**La mejora que quieres proponer hace relación a un problema?**
Ajustar texto en la pregunta ¿Tienes permiso para trabajar en el país donde vives?

Creo que falta un QUE: Para que al finalizar el bootcamp puedas conseguir trabajo, es necesario que estés apta para trabajar en el país, esto requiere **QUE** tengas los permisos necesarios para trabajar.

**Describe la solución que te gustaría**
Descripción clara y concisa de qué te gustaría que ocurra.

**¿Qué alternativas has considerado?**
Descripción clara y concisa de otras soluciones alternativas que hayas
considerado.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/191
