### ISSUE TITLE
problemas con mi resultado

### ISSUE THREAD

**Issue by Mary1505sm** [Laboratoria/tech-support#120]
const coinConvert = (dollars) => {
  const tasaSoles = 3.25;
  const tasaPesosMexicanos = 18;
  const tasaPesosChilenos = 660;
  
  const soles=dollars*tasaSoles;
  const pesosMexicanos=dollars*tasaPesosMexicanos;
  const pesosChilenos = dollars*tasaPesosChilenos;
  
  return[soles,pesosMexicanos,pesosChilenos];
  
  
};

const resultado1=coinConvert(50);
console.log(resultado1);
const resultado2=coinConvert(100);
console.log(resultado2);
const resultado3=coinConvert(85);
console.log(resultado3);

y cuando hago clic en ejecutar me sale :coinConvert()
debería retornar [162.5, 900, 33000], para $50
coinConvert is not a function

debería retornar [325, 1800, 66000], para $100
coinConvert is not a function

debería retornar [276.25, 1350, 49500], para $85
coinConvert is not a function

3 de 3 tests fallaron
(4ms)

**Comment by Romilton-Costa** [comment]
¡Hola Mary!
el error fue const soles=dollarstasaSoles; Habría que multiplicar dólares por tasaSoles. Entonces quedaría así const soles = dólares * tasaSoles;
const pesosMexicanos = dólares * tasaPesosMexicanos;
const Pesos Chilenos = dólares * tasa de Pesos Chilenos;
el código completo sería:


const coinConvert = (dollars) => {
    const tasaSoles = 3.25;
    const tasaPesosMexicanos = 18;
    const tasaPesosChilenos = 660;

    const soles = dollars * tasaSoles;
    const pesosMexicanos = dollars * tasaPesosMexicanos;
    const pesosChilenos = dollars * tasaPesosChilenos;

    return [soles, pesosMexicanos, pesosChilenos];
};

const resultado1 = coinConvert(50);
console.log(resultado1);
const resultado2 = coinConvert(100);
console.log(resultado2);
const resultado3 = coinConvert(85);
console.log(resultado3);

**Comment by Mary1505sm** [comment]
coinConvert()
debería retornar [162.5, 900, 33000], para $50
coinConvert is not a function

debería retornar [325, 1800, 66000], para $100
coinConvert is not a function

debería retornar [276.25, 1350, 49500], para $85
coinConvert is not a function

**Comment by Mary1505sm** [comment]
no me ejecuta y no entiendo por que

**Comment by adolivaresl** [comment]
Hola @Mary1505sm muchas gracias por reportarnos tu problema, por lo que muestras en tu código lo más probable que esté sucediendo es que en el editor en que tienes resuelto tu reto hayas borrado la última línea del boilerplate, que es la que toma el código y ejecuta los test. Te adjunto una imagen para que revises si lo tienes o no. (fijate en lo que he destacado en verde)

![muestra-boilerplate](https://github.com/Laboratoria/tech-support/assets/32287138/f2fd15ee-d6dc-4e81-a0cd-aa182767bdcb)

por otro lado, muchas gracias @romiltondev por tu aporte.

**Comment by Mary1505sm** [comment]
Muchas gracias!
