### ISSUE TITLE
problemas con ejecutar la prueba

### ISSUE THREAD

**Issue by Mary1505sm** [Laboratoria/tech-support#121]
const coinConvert = (dollars) => {
    const soles = dollars * 3.25;
    const pesosMexicanos = dollars * 18;
    const pesosChilenos = dollars * 660;
  
    return [soles, pesosMexicanos, pesosChilenos];
  };
  
  const cantidadDolares = 50;
  const conversion1 = coinConvert(cantidadDolares);
  console.log(conversion1); // Debería retornar [162.5, 900, 33000]
  
  const cantidadDolares2 = 100;
  const conversion2 = coinConvert(cantidadDolares2);
  console.log(conversion2); // Debería retornar [325, 1800, 66000]
  
  const cantidadDolares3 = 85;
  const conversion3 = coinConvert(cantidadDolares3);
  console.log(conversion3); // Debería retornar [276.25, 1350, 49500]

**Comment by adolivaresl** [comment]
cierro este issue en favor del que[ ya has reportado antes,](https://github.com/Laboratoria/tech-support/issues/120) porque veo que se trata del mismo problema.
