### ISSUE TITLE
[Bug] Mi postulacion sale expirada

### ISSUE THREAD

**Issue by dianagarciaortiz** [Laboratoria/tech-support#122]
**Describe el problema**
Terminé los retos satisfactoriamente pero al entrar a mi cuenta me marca que la postulacion esta expirada y no terminé a tiempo 

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a 'Mi cuenta'
2. Hacer click en 'Icono de mi cuenta'
3. Hacer scroll hacia abajo hasta 'Desarrollo Web-DEV009'
4. Ver error

**Comportamiento esperado**
Esperé que al terminar mis retos me salieran como terminados y enviados, justo como el primer reto.

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender el problema.
![image](https://github.com/Laboratoria/tech-support/assets/155931154/2e5c307f-75a9-43c8-8f33-bd4f0ca83ace)

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que ocurre el problema.
Al presionar el los tres puntos para mas opciones me dice que vuelva a cursar el reto, y cuando lo hago me muestra que mi postulacion ha sido enviada correctamente, quisiera estar segura de que se cumplieron los dos retos satisfactoriamente y los tienen registrados, muchas gracias <3 

![image](https://github.com/Laboratoria/tech-support/assets/155931154/aa7786bf-4ea7-4b70-b241-bf8fd0a7bdd2)

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/account`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by dianagarciaortiz** [comment]
> **Describe el problema** Terminé los retos satisfactoriamente pero al entrar a mi cuenta me marca que la postulacion esta expirada y no terminé a tiempo
> 
> **Para reproducirlo** Pasos para reproducir el problema:
> 
> 1. Ir a 'Mi cuenta'
> 2. Hacer click en 'Icono de mi cuenta'
> 3. Hacer scroll hacia abajo hasta 'Desarrollo Web-DEV009'
> 4. Ver error
> 
> **Comportamiento esperado** Esperé que al terminar mis retos me salieran como terminados y enviados, justo como el primer reto.
> 
> **Screenshots** Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender el problema. ![image](https://private-user-images.githubusercontent.com/155931154/313004254-2e5c307f-75a9-43c8-8f33-bd4f0ca83ace.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NTUxMzgsIm5iZiI6MTcxMDQ1NDgzOCwicGF0aCI6Ii8xNTU5MzExNTQvMzEzMDA0MjU0LTJlNWMzMDdmLTc1YTktNDNjOC04ZjMzLWJkNGYwY2E4M2FjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQyMjIwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjE1ZTY2Y2I3NWJiNzJhM2I3ZTY1MWMyNjJkNzQ5MjRlZWMxZmE2MWFjMmFkZWY3MzBiYzk5MTliYTU1MWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J3nzKcnmkmmQmk9qwVnIvw4dB8I0O6JMfCR7ZLf1wks)
> 
> **Contexto adicional** Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que ocurre el problema. Al presionar el los tres puntos para mas opciones me dice que vuelva a cursar el reto, y cuando lo hago me muestra que mi postulacion ha sido enviada correctamente, quisiera estar segura de que se cumplieron los dos retos satisfactoriamente y los tienen registrados, muchas gracias <3
> 
> ![image](https://private-user-images.githubusercontent.com/155931154/313004837-aa7786bf-4ea7-4b70-b241-bf8fd0a7bdd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NTUxMzgsIm5iZiI6MTcxMDQ1NDgzOCwicGF0aCI6Ii8xNTU5MzExNTQvMzEzMDA0ODM3LWFhNzc4NmJmLTRlYTctNGI3MC1iMjQxLWJmOGZkMGE3YmRkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQyMjIwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWNhY2U2Zjc3YjZiZGE0OTAyMmM0ZmZiOTc5NTlhNTI0MTc4YTM5NDUwNTM4OTJlYjBjMTU5MTNlZTNkNDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.STPhjNoCm-ROXvI9K7w9OpHAErD3pPHNp9HpwxtsSF4)
> 
> **Alerta** Recuerda que este repositorio es público, todos los issues y conversaciones relacionadas son públicas y visibles a todo el mundo. Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, nos pondremos en contacto para poder dar soporte a través de un canal privado.
> 
> ## Entorno
> **Location**: `https://bootcamp.laboratoria.la/es/account` **User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36` **Navigator Language**: `es-ES` **Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @dianagarciaortiz, gracias por comunicarte con nosotros. como puedes ver tienes dos postulaciones, la primera fue a DEV009, esa efectivamente ya expiró, porque no se envió a tiempo tu postulación, de hecho el cohort al que habías postulado inicialmente ya terminó el año pasado.
Pero tu segunda postulación que corresponde a DEV015, el cual es otro cohort y por lo tanto es otra aplicación independiente del que hiciste la primera vez (DEV009). El último mensaje que enviaste en la captura de pantalla corresponde al estado de tu ultima aplicación o sea el de DEV015.
Asi que no te preocupes, tu ultima postulación sigue en curso y ya pasó la fase online.
Espero esto te deje más tranquila, mucho éxito!
