### ISSUE TITLE
[Bug] Substitua este texto pelo título

### ISSUE THREAD

**Issue by privivid** [Laboratoria/tech-support#123]
Olá, boa tarde! Me chamo Priscila, e me inscrevi no bootcamp do Laboratória, de análise da dados, realizei o teste e enviei, estava no aguardo de uma resposta, e como não obtive, fui novamente verificar meus e-mails e havia um e-mail de Fevereiro para a inscrição. Minha dúvida é, mesmo tendo realizado todas as etapas até o teste, esse e-mail de 9 de Fevereiro tem algo com a espera de alguma resposta? O bootcamp iniciou em 11/03, e desde então nem uma e-mail sobre o envio do teste, eu recebi. 
Fico no aguardo, no mais, obrigada.

**Descreva o problema**
Descrição clara e concisa de qual é o problema.

**Para jogar**
Etapas para reproduzir o problema:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Descrição clara e concisa do que você esperava que acontecesse.

**Screenshots**
Se possível, adicione capturas de tela para ajudar a entender
o problema.

**Contexto adicional**
Adicione qualquer outra coisa que possa ajudar a entender o contexto em que
o problema ocorre.

**Alerta**
Lembre-se que este repositório é público, todos os problemas e conversas
relacionados são públicos e visíveis para todos.
Se você precisar compartilhar informações conosco em particular, NÃO faça isso por meio deste repositório,
Entraremos em contato com você para poder fornecer suporte por meio de um canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/pt/data?mc_cid=323f091c23&mc_eid=afffb5a2df`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0`
**Navigator Language**: `pt-BR`
**Selected Language**: `pt`

**Comment by vale-vanessa** [comment]
@privivid Boa tarde, tudo bem? Lhe enviamos o retorno através do e-mail  seleção@laboratoria.la
