### ISSUE TITLE
Los países me aparecen solo hasta las letra H

### ISSUE THREAD

**Issue by ShomaraQA** [Laboratoria/tech-support#124]
**Describe el problema**
Descripción clara y concisa de cuál es el problema.

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a '...'
2. Hacer click en '....'
3. Hacer scroll hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Descripción clara y concisa de qué esperabas que ocurriera.

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/apply?programId=4`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @ShomaraQA gracias por contactarte con nosotros, ¿podrías darme más contexto respecto a esto? ¿Es cuando estas respondiendo el formulario? ¿A que bootcamp estas postulando? por favor trata de darme toda la información que puedas para poder investigarlo.

**Comment by adolivaresl** [comment]
Bueno, @ShomaraQA, asumiré que es del formulario donde preguntan tu nacionalidad o donde preguntan tu lugar de residencia, en estos campos no se va a cargar toda la lista de países pero si digitas las tres primeras letras de tu país ya que va a aparecer opciones con esas letras.
Espero esto sea realmente la ayuda que necesitabas.
Muchas gracias por contactarte con nostros.
