### ISSUE TITLE
Hola tengo un par de preguntas sobre el próximo bootcamp de UX que van a realizar, pero no he encontrado un correo o contacto para realizarlas.  Me pueden brindar un correo de contacto? Gracias

### ISSUE THREAD

**Issue by male25** [Laboratoria/tech-support#126]
En este espacio puedes agregar el contexto necesario: texto, screenshots, etc.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es?utm_source=laboratoria_web&utm_campaign=footer_laboratoria-web&utm_medium=footer`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @male25, gracias por contactarnos, si quieres realizar tus preguntas sobre el bootcamp de UX puedes hacerlo a través de este correo: [postula@laboratoria.la](mailto:postula@laboratoria.la)
Espero tengas buen día.
