### ISSUE TITLE
Postulación a curso de Análisis de Datos en Laboratoria

### ISSUE THREAD

**Issue by conimoralesg** [Laboratoria/tech-support#127]
Buenas tardes, quisiera saber si puedo participar del curso de Análisis de Datos siendo chilena, pero viviendo en Alemania (Estoy con una Working Holiday por 1 año)

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/auth/signup`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`
**Navigator Language**: `es-CL`
**Selected Language**: `es`

**Comment by ib-frida** [comment]
Hola Coni, es necesario vivir en los países donde operamos.
