### ISSUE TITLE
Ajuste texto "explicación" - pregunta ¿Cuál es tu número de celular?

### ISSUE THREAD

**Issue by JulianaFacciolla** [Laboratoria/tech-support#13]
**La mejora que quieres proponer hace relación a un problema?**
Poner el punto final (.) en la frase abajo:
Si tienes cuenta de WhatsApp, usa ese número para que sea más fácil ponernos en contacto

**Describe la solución que te gustaría**
Descripción clara y concisa de qué te gustaría que ocurra.

**¿Qué alternativas has considerado?**
Descripción clara y concisa de otras soluciones alternativas que hayas
considerado.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
@rocioalberdi , ¿vale la pena priorizar esto? No vemos el valor que aportaría, aunque es un cambio rápido, no es una falta de ortografía.

**Comment by rocioalberdi** [comment]
No lo priorizaría
