### ISSUE TITLE
Sueldo - pregunta En tu ultimo trabajo, ¿Cuál era tu ingreso mensual? 

### ISSUE THREAD

**Issue by JulianaFacciolla** [Laboratoria/tech-support#14]
**Describe el problema**
Después de poner un monto y intentar borrar, no se puedo borrar por completo.

**Para reproducirlo**
Pasos para reproducir el problema:
Ejemplo:
He puesto un sueldo de 8000 soles.
Si quiero cambiarlo a 5000, sólo puedo borrar los 000. Ahí es necesario barrar hasta el 0 por las flechas a la derecha.
Creo que esto puede generar problemas en los sueldos y la pregunta es un filtro.

**Comportamiento esperado**
Devería poder borrar todo el numero

**Screenshots**
![Screen Shot 2023-02-26 at 13 30 49](https://user-images.githubusercontent.com/62949565/221423761-7677791f-ea62-4338-a863-6373cd595497.png)
![Screen Shot 2023-02-26 at 13 36 49](https://user-images.githubusercontent.com/62949565/221423777-20a3013d-a426-4e4a-9eea-1ac6e89bd431.png)

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Duplicado de: https://github.com/Laboratoria/tech-support/issues/28
