### ISSUE TITLE
Mensaje de no avanza en baseline

### ISSUE THREAD

**Issue by JulianaFacciolla** [Laboratoria/tech-support#15]
**Describe el problema**
El mensaje que aparece no es la versión final. 

Como explicado en el issue https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/63, hemos cambiado el texto, y la versión final debe ser:

¡Gracias por postular al bootcamp de Laboratoria! Nos encanta saber que cada vez hay más mujeres como tú con ganas de convertirse en desarrolladoras web o diseñadoras de experiencia de usuario.

Desafortunadamente, las respuestas que nos compartiste nos indican que no cumples con el perfil para seguir adelante en el proceso de selección del bootcamp de Laboratoria.

Si te interesa que evaluemos en profundidad tu caso, te invitamos a llenar este formulario:
https://laboratoria.typeform.com/to/uX9s3MVh.

¿Te interesa conocer un poco más de programación? A pesar de no poder postular, tienes la posibilidad de desarrollar los proyectos y acceder a contenidos que te ayudarán a conocer más de este mundo.

Si tienes más dudas, escríbenos a [[postula@laboratoria.la](mailto:postula@laboratoria.la)](mailto:[postula@laboratoria.la](mailto:postula@laboratoria.la)) y con gusto te ayudaremos.

¡Gracias, nuevamente!

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a '...'
2. Hacer click en '....'
3. Hacer scroll hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Descripción clara y concisa de qué esperabas que ocurriera.

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
@JulianaFacciolla, nos compartes por favor el texto en portugués. Gracias.

**Comment by adsotoh** [comment]
Resuelto en el release del milestone https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1
