### ISSUE TITLE
[Mejora] Visibilidad de opciones desplegables en las preguntas de linea base 

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#16]
Nice to have para otro release. 

<img width="1301" alt="Captura de Pantalla 2023-02-26 a la(s) 14 39 55" src="https://user-images.githubusercontent.com/29586691/221441906-9bcb9ab1-3675-47e6-b369-8c3029a67b96.png">

**La mejora que quieres proponer hace relación a un problema?**
Cuando quieres buscar tu país, nacionalidad, universidad sin escribirlo no puedes hacerlo, porque sólo te muestra un mínimo de opciones. Me gustaría poder hacer scroll y continuar viendo la lista de opciones, sino sólo veo las primeras que aparecen por orden alfabético. 

**Describe la solución que te gustaría**
Me gustaría que al hacer scroll down por las opciones que muestra la pregunta en linea base pueda continuar bajando y viendo las alternativas. Ahora sólo puedo ver un límite y si haces scroll down no puedes ver más que las que te muestra.

**¿Qué alternativas has considerado?**
Que al hacer scroll pueda continuar viendo la lista de opciones.

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/190
