### ISSUE TITLE
[Bug] Texto incorrecto al elegir Santiago de Chile, Lima o Bogotá

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#17]
Necesario para este release 

**Describe el problema**
Para aquellas que viven fuera de la capital se debiese desplegar el texto "Muchas organizaciones tienen su sede en las capitales de países donde operamos y, por lo tanto, es importante que estés disponible para cambiarte de ciudad si las vacantes que te interesan son presenciales. Sin embargo, hoy vemos que cada vez más empresas optan por formatos 100% remotos o híbridos. Es posible que conseguir un trabajo 100% remoto tome más tiempo." Actualmente se despliega tanto para las que no viven en la capital de los países dónde operamos como también a las que viven ahí. 
Este texto sólo debiese ser visto por aquellas que **no viven en la capital** de los países donde operamos. Este bug está cuando postulas a Chile, Perú y Colombia, no así en México o Ecuador. 

**Para reproducirlo**
Pasos para reproducir el problema:
1. Completar baseline eligiendo como país Chile, Perú o Colombia
2. En la pregunta ¿en qué ciudad o población vives? escoger Santiago de Chile, Región Metropolitana, Chile o Lima, Perú o Bogotá, Colombia.
3. Ver error. Se despliega texto para ciudades que no son capital. 

**Comportamiento esperado**
Al escoger Santiago de Chile, Región Metropolitana, Chile no debiese desplegarse el texto para ciudades fuera de la capital. 

**Screenshots**
<img width="1336" alt="Captura de Pantalla 2023-02-26 a la(s) 14 45 59" src="https://user-images.githubusercontent.com/29586691/221442188-ff74b4b0-fa51-4998-ba20-d2da37b5e5ba.png">

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Issue resuelto en el release del milestone https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1
