### ISSUE TITLE
[Mejora] Agregar texto en pregunta sobre hijos

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#18]
**La mejora que quieres proponer hace relación a un problema?**
Para un siguiente release sugiero que agreguemos un texto al lado de la pregunta "¿Cuántos hijos tienes?"  que diga "Si no tiene hijos ponga 0". Necesitamos ser explícitos con lo que deben colocar aquellas que no son mamás (que son la mayoría). 
Sugiero que el texto "Tenemos muchas estudiantes y egresadas que son mamás. Estas preguntas las hacemos para conocer mejor tu contexto" sólo se despliegue a aquellas que tienen 1 o más hijos. 
<img width="951" alt="Captura de Pantalla 2023-02-26 a la(s) 14 50 36" src="https://user-images.githubusercontent.com/29586691/221442381-484f714b-e819-42f3-9321-699bda05242d.png">

**Describe la solución que te gustaría**
Me gustaría que la pregunta sea formulada así: ¿Cuántos hijos tienes? Si no tiene hijos ponga 0" y aquellas que ponen 1 o más se muestre el texto "Tenemos muchas estudiantes y egresadas que son mamás. Estas preguntas las hacemos para conocer mejor tu contexto"

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
@rocioalberdi , no es posible solamente desplegar en un caso específico, pues es un placeholder que es parte del campo de texto. Sugiero que agreguemos el texto "Si no tienes hijos, escribe 0" enseguida de: Tenemos muchas estudiantes y egresadas que son mamás. Estas preguntas las hacemos para conocer mejor tu contexto.

Es decir, quedaría así:

Si no tienes hijos, escribe 0. Tenemos muchas estudiantes y egresadas que son mamás. Estas preguntas las hacemos para conocer mejor tu contexto.

**Comment by rocioalberdi** [comment]
De acuerdo con la propuesta @adsotoh

**Comment by adsotoh** [comment]
Cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/192
