### ISSUE TITLE
[Mejora] Formato número en moneda local pregunta sobre sueldo

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#19]
**La mejora que quieres proponer hace relación a un problema?**
Sugiero que el formato del número sea con la moneda. Ejemplo: si escribo 1000000 que se visualice 1.000.000 y así en cada moneda local para evitar errores. Es primera vez que ellas van a escribir el monto y no tendremos doble validación, es importante evitar que lo escriban incorrectamente, además es un dato muy importante ya que es una pregunta filtro, por lo que necesitamos que lo escriban correctamente. Además es un dato que reportamos muchísimo a los donantes y de uso interno en Laboratoria, por lo que debe ser lo más preciso.  
<img width="1271" alt="Captura de Pantalla 2023-02-26 a la(s) 14 55 18" src="https://user-images.githubusercontent.com/29586691/221442595-2beed488-a887-4dc8-a674-a7bbd977db3e.png">

**Describe la solución que te gustaría**
Agregar la puntuación de cada moneda local. Si escribo 1000000 que se visualice 1.000.000

**¿Qué alternativas has considerado?**
En caso que no sea posible que deban escribir el número dos veces para evitar errores. 

Si es algo sencillo sugiero intentar hacerlo. Sino que pase al siguiente release, es importante que salga pronto. 

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Resuelto en el release del milestone: https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1
