### ISSUE TITLE
[Mejora] Linea base pregunta sobre colegio/escuela

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#20]
**La mejora que quieres proponer hace relación a un problema?**
Agregar texto 
"Esta información no influye en tu proceso de postulación. Estas preguntas las hacemos para conocer mejor tu contexto."
<img width="1204" alt="Captura de Pantalla 2023-02-26 a la(s) 15 04 25" src="https://user-images.githubusercontent.com/29586691/221442829-7d5cb013-4954-42fc-b7f6-302f9c307b7a.png">

**Contexto adicional**
Es una pregunta nueva que puede ser sensible, por lo que agregaría ese texto para evitar conflicto por parte de las postulantes.

Puede pasar al siguiente release. 

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Issue cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/189
