### ISSUE TITLE
[Mejora] Agregar día a opciones de BC 

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#21]
**La mejora que quieres proponer hace relación a un problema?**
Lo conversamos en la demo, agregar día para ver las opciones de BC, ya que tendremos dos durante abril y no se pueden distinguir al momento de postular. 
<img width="1215" alt="Captura de Pantalla 2023-02-26 a la(s) 15 10 40" src="https://user-images.githubusercontent.com/29586691/221443125-2d5e6bb3-3290-4afb-a3b9-9cca7efeaa26.png">

Necesario para este release

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Issue actualmente siendo trabajado por Domi acá: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/153

**Comment by adsotoh** [comment]
Resuelto en https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1
