### ISSUE TITLE
[Mejora] Correo de re-establecer contraseña está en inglés 

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#22]
**La mejora que quieres proponer hace relación a un problema?**
Necesitamos que el correo sea en español. 
<img width="1084" alt="Captura de Pantalla 2023-02-23 a la(s) 09 15 47" src="https://user-images.githubusercontent.com/29586691/221443365-a9d1c7a2-d4d4-4b75-9ff5-edad99136e5e.png">

Necesario para salir
***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Resuelto en el milestone https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1
