### ISSUE TITLE
[Mejora] Agregar aviso cuando en linea base faltan datos o esta incompleto

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#23]
**La mejora que quieres proponer hace relación a un problema?**
Al enviar la linea base con datos incompletos no te da ningún feedback, para ver lo que te faltó debes revisar por tu cuenta el formulario. Si alguien no sabe que le faltó algo, puede pensar que el botón no está funcionando. Necesitamos un aviso que te diga que debes revisar o llenar campos que faltan. 

**Describe la solución que te gustaría**
Podría aparecer un mensaje en el app o ya sea un pop-up que te avise que debes revisar algo en el formulario. No es intuitivo como lo tenemos ahora.

**¿Qué alternativas has considerado?**
Mensaje en el app o pop-up

<img width="769" alt="Captura de Pantalla 2023-02-26 a la(s) 16 00 47" src="https://user-images.githubusercontent.com/29586691/221445594-6cb557d4-7909-48b2-ab9b-6eccae1f5d74.png">
<img width="918" alt="Captura de Pantalla 2023-02-26 a la(s) 16 00 52" src="https://user-images.githubusercontent.com/29586691/221445606-739c1e46-6a1f-4f07-ae3f-39a0716cd807.png">

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

Para el siguiente release

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/188
