### ISSUE TITLE
[Bug] No hay acceso a retos en caso de ser LB negativa

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#24]
Necesario para este MVP

**Describe el problema**
Aquellas que fueran línea base negativa deberían acceder a los retos, pero sus respuestas no serían consideradas en el proceso. 
Actualmente si eres línea base negativa no puedes visualizar los retos
Veo dos opciones
1. Cambiar el texto de línea base negativa para este release 
2. Darle acceso a los retos 
Por el tiempo diría que es mejor cambiar el texto para poder salir con el MVP y una vez que implementemos la funcionalidad podemos volver al texto original. 
Si es este el caso, sugiero que el texto sea: 

¡Gracias por postular al bootcamp de Laboratoria! Nos encanta saber que cada vez hay más mujeres como tú con ganas de convertirse en desarrolladoras web o diseñadoras de experiencia de usuario.

Desafortunadamente, las respuestas que nos compartiste nos indican que no cumples con el perfil para seguir adelante en el proceso de selección del bootcamp de Laboratoria.

Si quieres que evaluemos en profundidad tu caso, te invitamos a llenar [este formulario ](https://laboratoria.typeform.com/to/uX9s3MVh).

Si tienes más dudas, escríbenos a postula@laboratoria.la y con gusto te ayudaremos.

¡Gracias, nuevamente!

**Para reproducirlo**
Pasos para reproducir el problema:
1. completar baseline negativa para SCL con filtro de universidades de calidad 

**Comportamiento esperado**
Se esperaba que recibieran el mensaje de baseline negativa y pudieran ver el resto del proceso. 

**Screenshots**
<img width="1280" alt="Captura de Pantalla 2023-02-26 a la(s) 16 04 35" src="https://user-images.githubusercontent.com/29586691/221445904-2c2a1b19-4a84-4415-a213-68205a08e562.png">

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
@rocioalberdi, ¿este issue sigue siendo una prioridad para el equipo? Se modificó el texto ya en el release del milestone 1.0.0 y no tienen acceso a los retos las mujeres que no pasaron los filtros. Si sí queremos que tengan acceso a los filtros, necesitamos el texto que deberían ver y el diagrama de flujo de cómo ves ese caso de uso. :) 

cc @diegovelezg

**Comment by rocioalberdi** [comment]
Por ahora no lo priorizaría. 
En un principio Lupo planteo dejarle abierto los retos a todas para que puedan seguir avanzando y aprendiendo. Creo que por ahora no es una prioridad, si queremos que tengan acceso puede ser a través de la currícula y no necesariamente en la plataforma

**Comment by adsotoh** [comment]
Ok, entonces, con base en tu comentario, cerramos este issue y si vemos que se vuelve prioridad en el futuro, lo abrimos en el repo que consideremos, ya sea bootcamp o curricula.
