### ISSUE TITLE
[Mejora] Texto en perfil de postulación

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#25]
**La mejora que quieres proponer hace relación a un problema?**
Cuando eres línea base negativa y entras al perfil de tu postulación te aparece que está "en proceso". Sugiero que aquellas que sean linea base negativa vean un texto que diga "Postulación no aprobada". 

**Describe la solución que te gustaría**
Descrita en este [issue](https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/142) 

Para este release sí me parece necesario que al ser linea base negativa diga postulación no aprobada, ya que asocia con este issue [https://github.com/Laboratoria/tech-support/issues/29](url) de re-aplicante. Al estar en proceso la postulación, cuando en realidad fue rechazada, no puede re-aplicar en caso de querer hacerlo. 

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signin`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/187
