### ISSUE TITLE
[Mejora] Valores en pregunta household

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#26]
**La mejora que quieres proponer hace relación a un problema?**
Esta pregunta no debería aceptar valor 0. Hace referencia a cuántas personas viven en el hogar incluyéndote a ti, es decir, siempre sea 1 o mayor a eso. 

**Describe la solución que te gustaría**
no te permita respuesta con número igual a 0

<img width="992" alt="Captura de Pantalla 2023-02-26 a la(s) 16 46 55" src="https://user-images.githubusercontent.com/29586691/221448398-e909f010-f856-48fa-84e4-6bee551c276c.png">

Pasa a siguiente release 

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/187
