### ISSUE TITLE
[Mejora] Datos dentro del perfil

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#27]
**La mejora que quieres proponer hace relación a un problema?**
Actualmente dentro de los datos se encuentra la pregunta ¿te identificas como mujer? Esta pregunta no debiese ser editable, dado que es un filtro dentro del proceso de selección. Además, si el perfil es utilizado por más usuarios de Laboratoria me parece irrelevante preguntar su identificación de genero. 

**Describe la solución que te gustaría**
Quitar esta pregunta dentro de los datos del perfil. 

<img width="538" alt="Captura de Pantalla 2023-02-26 a la(s) 20 57 56" src="https://user-images.githubusercontent.com/29586691/221478143-1004e7fc-709e-454f-845f-f653f901f041.png">

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/account`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/186
