### ISSUE TITLE
[Bug] No puedo borrar un número que escribí

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#28]
**Describe el problema**
Al escribir tu salario o ingreso familiar no puedes borrar el primer número. Esto me ocurrió postulando a Ecuador. 

**Para reproducirlo**
Pasos para reproducir el problema:
1. Postular en Ecuador
2. En salario individual poner 5000, ingresar el número e intentar borrarlo
3. Ver error, no puedes borrar el 5
 
<img width="1242" alt="Captura de Pantalla 2023-02-26 a la(s) 22 22 19" src="https://user-images.githubusercontent.com/29586691/221489883-a5ce1c77-8900-4baf-ac11-ad99c48d6b65.png">

<img width="1204" alt="Captura de Pantalla 2023-02-26 a la(s) 22 26 28" src="https://user-images.githubusercontent.com/29586691/221490545-949496f2-4f80-4fc1-a8f4-b02099d9742f.png">

Necesario para salir 

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Bug ligado al issue en el milestone 1.0.0 https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/146

**Comment by biancosbag** [comment]
Te permite borrar todos los dígitos si es que los seleccionas al mismo tiempo; de otra manera, no.

**Comment by adsotoh** [comment]
Resuelto en el milestone: https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1
