### ISSUE TITLE
[Bug] No puedo re-aplicar si fui linea base negativa

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#29]
Necesario para este release

**Describe el problema**
Como re-aplicante quiero poder postular a un cohort de Laboratoria. 
Actualmente fui linea base negativa, y quiero postular nuevamente, pero el sistema no me lo permite porque ya tengo una postulación en proceso. 
1. Al tener una postulación en proceso no puede postular a otro BC de web dev
2. Al ser linea base negativa mi postulación no debiese ser "en proceso", ya que fue "no aprobada" y debería poder postular nuevamente. 

**Comportamiento esperado**
Cualquier re-aplicante que no tiene una postulación en proceso debería poder postular nuevamente. 
Además, si soy re-aplicante debería poder postular al BC de UX y web DEV a pesar de que estén ambos en proceso. 

**Screenshots**

<img width="1239" alt="Captura de Pantalla 2023-02-26 a la(s) 22 35 45" src="https://user-images.githubusercontent.com/29586691/221492405-4abc65a5-c97f-4d31-ac41-0647905bfdcf.png">
<img width="1331" alt="Captura de Pantalla 2023-02-26 a la(s) 22 35 56" src="https://user-images.githubusercontent.com/29586691/221492417-045c188e-c685-47d6-afdc-5686ee80d51d.png">

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/account`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/144
