### ISSUE TITLE
[Mejora] Fecha de inicio del bootcamp - Registro

### ISSUE THREAD

**Issue by biancosbag** [Laboratoria/tech-support#32]
**La mejora que quieres proponer hace relación a un problema?**
A la hora de elegir la FECHA DE INICIO DEL BOOTCAMP, aparecen 3 opciones: abril 2023 / mayo 2023 / mayo 2023. La homonimidad de estos 2 últimos bootcamps es confusa.

**Describe la solución que te gustaría**
Deberíamos diferenciarlo como lo hacíamos antes: mayo-I 2023 / mayo-II 2023

**¿Qué alternativas has considerado?**
mayo-A 2023 / mayo-B 2023
mayo-1 2023 / mayo-2 2023

**Contexto adicional**
De esta manera sabrán que sí existen 3 opciones de bootcamps por el momento y no se trata de un bug.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

**Comment by adsotoh** [comment]
Resuelto en el release del milestone: https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1

**Comment by biancosbag** [comment]
> Resuelto en el release del milestone: https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1

Me brindas acceso por fa? 😀

**Comment by adsotoh** [comment]
> > Resuelto en el release del milestone: https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1
> 
> Me brindas acceso por fa? 😀

@biancosbag, es el milestone en el cual hicimos el primer release de la plataforma a producción. ;)
