### ISSUE TITLE
[Mejora] Click al botón "Postular" con campos por rellenar

### ISSUE THREAD

**Issue by biancosbag** [Laboratoria/tech-support#33]
**La mejora que quieres proponer hace relación a un problema?**
A la hora de "Postular" y tener campos erróneos/vacíos, no sucede nada. La estudiante debe buscar en la página si hay algún error. Esto podría llevar a una frustración y hacer que cierren la página.

**Describe la solución que te gustaría**
Debería aparecerles un pop-up con el mensaje: "Aún tienes campos por rellenar" y/o scrollear automáticamente hacia esos campos.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

**Comment by adsotoh** [comment]
@biancosbag, no podemos reproducir esta mejora que mencionas. ¿Puedes pasar a la plataforma en staging y decirnos si sigue sucediendo? Y, si sigue sucediendo, dejar pasos más claros sobre cómo reproducir.

**Comment by biancosbag** [comment]
@adsotoh si gustas podemos verlo en una sesión rápida de 15min. En realidad es un tema simple de experiencia de usuaria, que ayudaría a optimizar el rate de conversión.

**Comment by adsotoh** [comment]
> @adsotoh si gustas podemos verlo en una sesión rápida de 15min. En realidad es un tema simple de experiencia de usuaria, que ayudaría a optimizar el rate de conversión.

Igual necesitamos claridad de los pasos para reproducir el error, y lo mejor es describirlos en el issue, entonces sugiero que sea asíncrono.

**Comment by lupomontero** [comment]
@adsotoh, creo que el problema sí es reproducible y hasta puede ser que ya exista un issue en algún otro lado para esto... lo que ocurre, corrígeme @biancosbag si me equivoco, es que al enviar el formulario de postulación, si algún campo que queda por encima del fold tiene algún error de validación no es obvio saber lo que pasó, ya que no cambia nada en la parte del formulario que podemos ver en la pantalla en ese momento, y solo nos daremos cuenta de que nos faltó llenar un campo o que pusimos algo mal si hacemos scroll hacia arriba y que se vean los campos en cuestión.

La solución debería enfocar el navegador (`.focus()`) en el primer campo que contenga error, de esa forma la usuaria se daría cuenta de inmediato que hay que corregir un error.

Esto es algo que hemos querido hacer desde el principio y en algún momento deberíamos implementar. Además, esto afectaría directamente o indirectamente también a cualquier otro formulario (en mobile la mayoría de forms requieren scroll para llegar a los botones de abajo y por ende son susceptibles al mismo problema de usabilidad).
