### ISSUE TITLE
[Mejora] Bootcamp UX cerrado

### ISSUE THREAD

**Issue by biancosbag** [Laboratoria/tech-support#34]
**La mejora que quieres proponer hace relación a un problema?**
El bootcamp de UX está cerrado y la ficha sigue apareciendo en el inicio.

**Describe la solución que te gustaría**
Quizá deberíamos dejar el diseño pero bajo una versión "apagada"?

**¿Qué alternativas has considerado?**
Otra opción más sencilla sería quitar la tarjeta por el momento.

**Contexto adicional**
![mejora  bootcamp ux](https://user-images.githubusercontent.com/105886859/221643039-e7a2cb04-ad7c-47a6-afc2-4dd63d9802e1.png)

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

**Comment by adsotoh** [comment]
@biancosbag , es informativo y es parte de la definición que se hizo de la UI de esa página. Además, comunicamos abajo que se abrirán postulaciones próximamente. 

cc @rocioalberdi , ¿qué opinas?

**Comment by biancosbag** [comment]
Dale! Eso ya lo vemos con Arlene en la mejora de UI más adelante.
