### ISSUE TITLE
Resultado "ejecutar pruebas"

### ISSUE THREAD

**Issue by JulianaFacciolla** [Laboratoria/tech-support#37]
**La mejora que quieres proponer hace relación a un problema?**

**Describe la solución que te gustaría**
Al hacer clic en Ejecutar puebas" debería aparecer los checks verdes. Esto porque puede generar dudas ya que no aparece nada. Yo misma he clicado 3-4 veces antes de bajar la página.
![Screen Shot 2023-02-27 at 19 44 19](https://user-images.githubusercontent.com/62949565/221703442-33086d29-8fd0-4247-a7ce-75a2b528fc8d.png)

**¿Qué alternativas has considerado?**
Descripción clara y concisa de otras soluciones alternativas que hayas
considerado.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Relacionado con: #40
