### ISSUE TITLE
[Bug] Campos pre-llenados tras cambio de país 

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#38]
**Describe el problema**
Si seleccionas un país en el que resides, luego eliges la ciudad, y quieres cambiar de país por algún error, el campo de ciudad no se re-inicia como el de teléfono. Debería ser igual y volver a estar en blanco. 
<img width="1241" alt="Captura de Pantalla 2023-02-27 a la(s) 20 46 06" src="https://user-images.githubusercontent.com/29586691/221756595-16f4638d-6558-4377-b95f-72ee363359cf.png">

Puede quedar para otro release

**Comment by adsotoh** [comment]
Resuelto en el release del milestone: https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1
