### ISSUE TITLE
[Bug] Filtro de Universidades incorrecto en EC

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#39]
**Describe el problema**
La Escuela Politécnica Nacional, Universidad Casa Grande, Universidad de las Fuerzas Armadas - ESPE, Universidad Católica de Santiago de Guayaquil, Universidad San Francisco de Quito, Universidad Espíritu Santo, Universidad de las Américas, UISEK - Universidad Internacional SEK Ecuador, Universidad Del Pacífico y Blue Hill College debiesen ser filtro de educación superior y no está siendo considerada un filtro. Revisar datos [acá]

<img width="1155" alt="Captura de Pantalla 2023-02-27 a la(s) 21 33 21" src="https://user-images.githubusercontent.com/29586691/221763434-fa3a9a43-f420-4781-b50e-e4c99ba8b571.png">

<img width="1155" alt="Captura de Pantalla 2023-02-27 a la(s) 21 33 21" src="https://user-images.githubusercontent.com/29586691/221763154-e4e6b792-6f2b-4815-9a13-09e65afead8e.png">

<img width="1309" alt="Captura de Pantalla 2023-02-27 a la(s) 21 28 18" src="https://user-images.githubusercontent.com/29586691/221762763-130a52ca-eb1b-4509-98d0-ca2a1815e496.png">
<img width="1110" alt="Captura de Pantalla 2023-02-27 a la(s) 21 30 47" src="https://user-images.githubusercontent.com/29586691/221762772-8b3ddbb1-05f6-4fa2-a88e-f1c4551ebe8d.png">

<img width="1169" alt="Captura de Pantalla 2023-02-27 a la(s) 21 28 10" src="https://user-images.githubusercontent.com/29586691/221762393-4de567cc-2739-4e79-b072-c809451bfb45.png">
<img width="1309" alt="Captura de Pantalla 2023-02-27 a la(s) 21 28 18" src="https://user-images.githubusercontent.com/29586691/221762408-0510bab9-e7f5-49ca-bc72-c035a1265b5d.png">

<img width="1198" alt="Captura de Pantalla 2023-02-27 a la(s) 21 24 27" src="https://user-images.githubusercontent.com/29586691/221761897-c7da0ee8-ed1a-40ec-a83d-bba67c9d5111.png">
<img width="1276" alt="Captura de Pantalla 2023-02-27 a la(s) 21 24 40" src="https://user-images.githubusercontent.com/29586691/221761916-6d0a177a-9860-4464-9eda-d4b9ded4d139.png">

(https://docs.google.com/spreadsheets/d/1T5onSBnNsNOBGaVJHeBq8RFRDhwsbiq-R5_IihqAl7Y/edit#gid=778292795&fvid=1671838409). 
<img width="1215" alt="Captura de Pantalla 2023-02-27 a la(s) 21 18 35" src="https://user-images.githubusercontent.com/29586691/221761166-526bab76-813a-4b1f-aaa0-5813eb6d6100.png">
<img width="1233" alt="Captura de Pantalla 2023-02-27 a la(s) 21 20 29" src="https://user-images.githubusercontent.com/29586691/221761404-e25dcee1-0e13-4f54-ac84-86696c9005bd.png">
<img width="1390" alt="Captura de Pantalla 2023-02-27 a la(s) 21 18 19" src="https://user-images.githubusercontent.com/29586691/221761427-0f382fc3-ec31-4b7b-a88a-443edf542102.png">

Por favor revisen bien la lista que añadieron. No sé si faltó activar el filtro o si agregaron como filtro alguna incorrectamente. 

Es necesario que esto este funcionando para salir.

**Comment by adsotoh** [comment]
Resuelto en el milestone: https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1
