### ISSUE TITLE
No queda claro que se ejecutaron correctamente los test

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#40]
**La mejora que quieres proponer hace relación a un problema?**
No queda claro que se ejecutaron correctamente los test o que se completo. Tiene que haber una mejor interacción en esta pantalla. Ya sea un texto de felicidades o algún cambio claro que se ejecutó correctamente. No debería poder editar el ejercicio o volver a correrlo una vez se ejecuta bien. Es confuso y no queda claro que está completo. 

<img width="1219" alt="Captura de Pantalla 2023-02-27 a la(s) 21 46 14" src="https://user-images.githubusercontent.com/29586691/221765302-b4784f21-a76e-443d-8834-c334b7b1a77e.png">

Sí es necesario que para salir este claro que quedó completo y no puedan volver a hacerlo nuevamente.

**Describe la solución que te gustaría**
Descripción clara y concisa de qué te gustaría que ocurra.

**¿Qué alternativas has considerado?**
Descripción clara y concisa de otras soluciones alternativas que hayas
considerado.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
@rocioalberdi , necesitamos que nos digas qué solución te gustaría para este caso, si es con mock ups o wireframes, mejor. 

Además, podríamos tomar de una vez en consideración el comentario que nos dio @anabellmora: 

> Hemos tenido preguntas sobre la "cantidad de veces" que pueden enviar un ejercicio, es decir confunden los items que tienen que entregar con la cantidad de veces que pueden hacer intentos de envío.

**Comment by rocioalberdi** [comment]
@adsotoh este issue estaría realacionado con este? 

https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/176

**Comment by adsotoh** [comment]
Correcto, @rocioalberdi . Voy a cerrar este en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/176
