### ISSUE TITLE
[Mejora] UX/UI retos

### ISSUE THREAD

**Issue by rocioalberdi** [Laboratoria/tech-support#41]
**La mejora que quieres proponer hace relación a un problema?**
No queda clara la completitud de los retos. Arlene había diseñado otra pantalla dónde quedaba más claro si fue o no completado. 
Es un gran tema en customer service la completitud/progreso, debe ser claro para no tener problemas hacia las postulantes. 

Sí lo veo necesario para salir. 

<img width="1262" alt="Captura de Pantalla 2023-02-27 a la(s) 21 48 35" src="https://user-images.githubusercontent.com/29586691/221765669-a4afc4c7-f06b-4da4-9091-49d377ff82b9.png">

**Describe la solución que te gustaría**
Descripción clara y concisa de qué te gustaría que ocurra.

**¿Qué alternativas has considerado?**
Descripción clara y concisa de otras soluciones alternativas que hayas
considerado.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Resuelto en el release del milestone: https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1
