### ISSUE TITLE
[Bug] Filtro: ¿En qué universidad estudiaste?

### ISSUE THREAD

**Issue by ib-frida** [Laboratoria/tech-support#44]
El filtro de universidad Privada y Pública no funciona
La lista de universidades está mezclada, entonces es inútil a la hora de hacer el proceso, no excluye universidades públicas al hacer click en "estudio en universidad privada" y viceversa.

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a registro
2. Hacer click en Privado/Público
3. Hacer scroll para ver las opciones
4. Ver error

**Comportamiento esperado**
Debe dar la lista proporcionada, filtrada por universidad Pública y Privada

**Screenshots**
![image](https://user-images.githubusercontent.com/95553392/221935683-a9ceff03-83f2-4010-9fd3-7f7b4da6cd62.png)

**Contexto adicional**
Puede llegar a ocasionar errores que influyan en la línea base

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 OPR/95.0.0.0`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Duplicado de: Laboratoria/bootcamp.laboratoria.la#251
