### ISSUE TITLE
[Bug] Lista de universidad

### ISSUE THREAD

**Issue by ib-frida** [Laboratoria/tech-support#45]
**El universo de universidades está incompleto**
Faltan instituciones en el listado de universidades.

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a 'Educación'
2. Hacer click en 'En dónde estudias'
3. Hacer scroll en el listado.
4. Ver error

**Comportamiento esperado**
De no entrar en ninguna de las universidades, la postulante NO puede seguir con su proceso.

**Sugiero agregar la opción de "OTRO"**

**Screenshots**
![image](https://user-images.githubusercontent.com/95553392/221939459-c55d5726-1486-44b9-9fec-ec1efdbfca10.png)

**Contexto adicional**
Es importante para el filtro y para el proceso

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 OPR/95.0.0.0`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/190
