### ISSUE TITLE
[Mejora] UX/UI: Cuadro de texto

### ISSUE THREAD

**Issue by ib-frida** [Laboratoria/tech-support#46]
**Cambiar colores dependiendo de la urgencia de la actividad requerida**
Modificar colores para generar un sentido de urgencia dentro del recorrido de la aplicante. El color azul no genera esta urgencia para terminar el proceso.

**Paleta de colores**
Rojo: Urgente
Amarillo: Aviso
Verde: ¡Todo bien!
**Ejemplos**
![image](https://user-images.githubusercontent.com/95553392/221936559-6f50a4fe-9359-42e0-bc4e-dff481de5a8d.png)

De azul a amarillo

![image](https://user-images.githubusercontent.com/95553392/221940014-3b8ff00e-c0ca-4fba-a2c0-be2b5f42c9a2.png)

De azul a rojo

**Contexto adicional**
Es importante para Admisiones que terminen su proceso, y el diseño puede alentar la finalización próxima de la postulante.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 OPR/95.0.0.0`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
@rocioalberdi, ¿qué opinas? Con la propuesta, es importante tomar en cuenta los diferentes casos de uso que podrían surgir en caso de priorizar algo así. Por ejemplo, en el caso que pone Frida de cambiar de azul a rojo el aviso a la postulante sobre hasta cuándo tiene para mandar su postulación, tendríamos que considerar que no en todos los casos el aviso debería ser rojo, pues si tienes suficiente tiempo para hacer tus retos, ¿por qué aplicaría el sentido de urgencia?

Creemos que, entre más pensamos en esos casos, más se complica, y no creemos que sea un stopper para que las postulantes manden su postulación.

**Comment by rocioalberdi** [comment]
De acuerdo @adsotoh puede complejizar y confundir
