### ISSUE TITLE
Cambio texto introducción retos

### ISSUE THREAD

**Issue by JulianaFacciolla** [Laboratoria/tech-support#47]
**Describe el problema**
Actualización del texto con Diego.

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a '...'
2. Hacer click en '....'
3. Hacer scroll hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Incluir el contenido en el párrafo de intriducción.
**Sigue texto nuevo:**

¡Bienvenida al proceso de selección a Laboratoria!

Debes sentirte muy orgullosa de estar dispuesta a invertir tu tiempo y esfuerzo para completar una de las etapas más importantes del proceso.

Esta etapa consiste en realizar los siguientes retos. No necesitas tener conocimientos previos de programación para realizar los retos. Dentro de cada uno encontrarás el material que te ayudará a aprender y adquirir los conocimientos necesarios para resolverlos con éxito.

Comenzarás desde cero, aprendiendo los fundamentos de JavaScript, el lenguaje de programación más popular del mundo.  El tiempo que te tome, puede variar dependiendo de tu propio ritmo. Estimamos que podría ser hasta 7 horas por cada reto.

Te recomendamos organizarte con tiempo para que vayas haciéndolo poco a poco. 

Para pasar a la siguiente etapa del proceso de selección es necesario que completes correctamente ambos retos. 

Recuerda que no estás sola en este proceso. Si tienes alguna duda puedes escribir a través del correo postula@laboratoria.la.

¡Mucha suerte!

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Resuelto en el release del milestone: https://github.com/Laboratoria/bootcamp.laboratoria.la/milestone/1
