### ISSUE TITLE
Cuando doy click en Laboratoria ( side menu)

### ISSUE THREAD

**Issue by reginaacher** [Laboratoria/tech-support#48]
**Describe el problema**
Descripción clara y concisa de cuál es el problema.

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a '...'
2. Hacer click en '....'
3. Hacer scroll hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Descripción clara y concisa de qué esperabas que ocurriera.

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by reginaacher** [comment]
Cuando doy click en Laboratoria ( side menu) - salie de la pagina de application

**Comment by adsotoh** [comment]
@reginaacher , es el comportamiento esperado, pues en toda página web, cuando se da clic al logo o al ícono de home, redirige a la home del sitio web. Y, en este caso, no olvidemos que no es la página de postulación sino de todo el journey de las personas que pasan por Laboratoria.
