### ISSUE TITLE
hola, como resuelvo esto? Calcula la potencia de 2 elevado a un número específico. Debes de usar un loop (no Math.pow()).

### ISSUE THREAD

**Issue by Ane118** [Laboratoria/tech-support#51]
En este espacio puedes agregar el contexto necesario: texto, screenshots, etc.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://curriculum.laboratoria.la/es/web-dev/gym`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
@ib-frida, te asignamos el issue para que nos apoyes respondiendo a la postulante.

**Comment by adsotoh** [comment]
Issue cerrado, pues el equipo responderá a la postulante por correo.
