### ISSUE TITLE
¿Cómo es la solución de la sección 3 del reto de portafolio? 

### ISSUE THREAD

**Issue by KeyraJolenne** [Laboratoria/tech-support#55]
Hola, estoy atorada en el proceso de selección con el reto de portafolio enla sección 3, justamente donde hay que añadir imagen con los atributos alt y src.

Me sale el siguiente error: 
etiquetas <img> deberían tener atributos src y alt esperados
expected 'https://images.unsplash.com/photo-151…' to equal 'https://images.unsplash.com/photo-151…'

Mi solución es la siguiente: 
 <figure>
    <img
      src="https://images.unsplash.com/photo-1519681393784"
      alt="Figure 1"
    >
    <figcaption><title>Figure 1</title></figcaption>
  </figure>
  <figure>
    <img
     src="https://images.unsplash.com/photo-1483728642387"
     alt="Figure 2"
    >
    <figcaption><title>Figure 2</title></figcaption>
  </figure>
  <figure>
    <img
     src="https://images.unsplash.com/photo-1454496522488"
     alt="Figure 3"
    >
    <figcaption><title>Figure 3</title></figcaption>
  </figure>
  <figure>
    <img
      src="https://images.unsplash.com/photo-1465056836041"
      alt="Figure 4"
    >
    <figcaption><title>Figure 4</title></figcaption>
  </figure>
  <figure>
    <img
      src="https://images.unsplash.com/photo-1464822759023"
      alt="Figure 5"
    >
    <figcaption><title>Figure 5</title></figcaption>
  </figure>

Gracias, espero su apoyo.

**Comment by angiektvr** [comment]
no aparece nada ahi en lo que mandaste

**Comment by ib-frida** [comment]
¡Hola! 

Te compartimos este [link](https://laboratoria-1.gitbook.io/recursos-para-el-pre-trabajo?utm_source=gitbook&utm_medium=front&utm_campaign=admissions_latam&utm_content=resources_dev) donde encontrarás más información que te ayudará a resolver los ejercicios de código del Pre-Trabajo.

Por favor escríbenos nuevamente si tienes alguna otra duda.

¡Gracias!

**Comment by adsotoh** [comment]
Se cerrará el issue porque @ib-frida ya dio seguimiento a la postulante.
