### ISSUE TITLE
Error al cargar el reto1 de bootcamp de Desarrollo Webb

### ISSUE THREAD

**Issue by MichellePerezS** [Laboratoria/tech-support#56]
Hola estaba haciendo el reto1  de bootcamp de Desarrollo Web y le di a ejecutar y me salía un error, pero luego me apareció la página en blanco y ya no pude visualizar más la página y no me deja hacer el reto2, comparto screenshot, el correo con el que me registré es: elyzabethperez.s@gmail.com.
Gracias! 

![Screenshot 2023-03-29 at 09 42 09](https://user-images.githubusercontent.com/55998893/228575509-5de032ce-bf10-483a-9fe6-eff24c0e7615.png)

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/account`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Hola, @MichellePerezS. ¿El problema que reportas sigue sucediendo?

**Comment by ib-frida** [comment]
Hola Michelle, te escribo por correo
