### ISSUE TITLE
No puedo acceder al pre trabajo, ayuda por favor

### ISSUE THREAD

**Issue by lolo262** [Laboratoria/tech-support#58]
No puedo acceder al pre trabajo de postulación
Realicé las dos postulaciones al Bootcamp de Desarrollo Web
Dos veces realicé los dos retos 
Y en ninguna de las dos postulaciones la plataforma me permite acceder al pre trabajo,
adjunto pantallazo de mi LMS
![2023-04-03 (11)](https://user-images.githubusercontent.com/82346880/229648324-c5335e0d-4ee3-4a25-a56a-75d64967e5c0.png)
![2023-04-03 (12)](https://user-images.githubusercontent.com/82346880/229648564-4cf4fb8e-7a42-4e32-8af6-1f5c77e90378.png)

**Comment by adsotoh** [comment]
Se cerrará el issue porque @ib-frida ya dio seguimiento a la postulante por correo.
