### ISSUE TITLE
Requiero ayuda en mi postulación 

### ISSUE THREAD

**Issue by KarinaDiaz03121995** [Laboratoria/tech-support#61]
He realizado el proyecto, pero no puedo con una de las acciones, me dice lo siguiente:

"etiquetas <figcaption> deberían tener texto esperado
expected '\nFigure 1\n ' to equal 'Figure 1'"

comparto mi proyecto para que me ayuden a identificar qué estoy haciendo mal. 
Muchísimas gracias por el apoyo.

<!DOCTYPE html>
</head>
<body>
  <header>
    <h1>Jane Doe</h1>
  </header>
  <aside>
    <ul>
      <li><a href="mailto:jane@doe.com">Contact</a>: Link al correo jana@doe.com.</li>
      <li><a href="https://www.google.com/search?q=jane+doe">About</a>: link a https://www.google.com/search?q=jane+doe</li>
    </ul>
  </aside>
  <main>
     <h2>Work</h2>
     <figure>
  <img
    alt="Figure 1"
    width="160"
    src="https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80"/>
  <figcaption>
Figure 1
  </figcaption>
</figure>
 <figure>
  <img
    alt="Figure 2"
    width="160"
    src="https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80"/>
  <figcaption>
Figure 2
  </figcaption>
</figure>
 <figure>
  <img
    alt="Figure 3"
    width="160"
    src=" https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80"/>
  <figcaption>
Figure 3
  </figcaption>
</figure>
 <figure>
  <img
    alt="Figure 4"
    width="160"
    src="https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80"/>
  <figcaption>
Figure 4
  </figcaption>
</figure>
 <figure>
  <img
    alt="Figure 5"
    width="160"
    src=" https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"/>
  <figcaption> 
  Figure 5
  </figcaption>
</figure>
  </main>
   <footer>  <h8>Jane Doe &copy; 2023</h8>
   <body>
  <html>

**Comment by adsotoh** [comment]
@ib-frida

**Comment by ib-frida** [comment]
¡Hola! 

Te compartimos este [link](https://laboratoria-1.gitbook.io/recursos-para-el-pre-trabajo?utm_source=gitbook&utm_medium=front&utm_campaign=admissions_latam&utm_content=resources_dev) donde encontrarás más información que te ayudará a resolver los ejercicios de código del Pre-Trabajo.

Por favor escríbenos nuevamente si tienes alguna otra duda.

¡Gracias!
