### ISSUE TITLE
[Pregunta] Reemplaza este texto con el título

### ISSUE THREAD

**Issue by CamilaUrrego** [Laboratoria/tech-support#62]
En este espacio puedes agregar el contexto necesario: texto, screenshots, etc.

**Alerta**
Buen dia, estoy presentando los retos para la inscripcion en laboratoria pero me sigue arrojando el mismo error, no entiendo porque, me podrian ayudar por favor
![image](https://user-images.githubusercontent.com/83282332/231524153-7da21767-f36c-4bde-8881-e3644b0e2a51.png)

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/account`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
@ib-frida

**Comment by ib-frida** [comment]
¡Hola! 

Te compartimos este [link](https://laboratoria-1.gitbook.io/recursos-para-el-pre-trabajo?utm_source=gitbook&utm_medium=front&utm_campaign=admissions_latam&utm_content=resources_dev) donde encontrarás más información que te ayudará a resolver los ejercicios de código del Pre-Trabajo.

Por favor escríbenos nuevamente si tienes alguna otra duda.

¡Gracias!
