### ISSUE TITLE
[Pregunta] Cuando es disparado el evento `sign_up` de analytics

### ISSUE THREAD

**Issue by bouli** [Laboratoria/tech-support#63]
Necesitamos saber: 
- Cuando exactamente es disparado el evento `sign_up` de google analytics en el nuevo sistema `core` en el domínio bootcamp.laboratoria.la?

Actualmente estamos trabajando con una agencia y necesitamos estar seguros de que estamos midiendo el mismo dato en analytics y en nuestros dashboards,.

cc: @JulianaFacciolla @adsoncostanzifilho

**Comment by adsotoh** [comment]
Cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/200
