### ISSUE TITLE
problemas con las postulación de desarrollador web

### ISSUE THREAD

**Issue by danapineiro** [Laboratoria/tech-support#65]
hola, estoy tratando de hacer las pruebas para postularme como desarrollador web pero me sale un error.

Uncaught SyntaxError: Unexpected token 'return' específicamente me sale eso cuando le doy en ejecutar pruebas..

Quisiera saber que debo hacer?

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/auth/signin`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Hola, @danapineiro . ¿Puedes poner capturas de pantalla del error que estás teniendo? Podría ser haya ejecutado las pruebas sin haber codeado y luego al hacerlo correctamente el mensaje se haya mantenido, pero necesitamos ver tu pantalla para estar seguros. Gracias.

**Comment by danapineiro** [comment]
Ese es el error es que ni he podido empezar las pruebas le doy y me sale ese mensaje Enviado desde mi iPhoneEl 25-04-2023, a la(s) 12:38, adsotoh ***@***.***> escribió:﻿
Hola, @danapineiro . ¿Puedes poner capturas de pantalla del error que estás teniendo? Podría ser haya ejecutado las pruebas sin haber codeado y luego al hacerlo correctamente el mensaje se haya mantenido, pero necesitamos ver tu pantalla para estar seguros. Gracias.

**Comment by adsotoh** [comment]
No es posible ver la captura, puedes subirla de nuevo? Gracias

**Comment by danapineiro** [comment]
Aquí está nuevo Enviado desde mi iPhoneEl 25-04-2023, a la(s) 12:59, adsotoh ***@***.***> escribió:﻿
No es posible ver la captura, puedes subirla de nuevo? Gracias

**Comment by adsotoh** [comment]
Dana, intenta solamente dejar un comentario sin responderme o hacerlo directamente desde github, porque sigue sin verse la captura. Por favor, gracias.

**Comment by danapineiro** [comment]
Ya lo hago Enviado desde mi iPhoneEl 25-04-2023, a la(s) 13:06, adsotoh ***@***.***> escribió:﻿
Dana, intenta solamente dejar un comentario sin responderme o hacerlo directamente desde github, porque sigue sin verse la captura. Por favor, gracias.

**Comment by danapineiro** [comment]
![image0 (1)](https://user-images.githubusercontent.com/131730743/234358270-b1af3c6e-a9c3-42e1-bdea-0d896a233720.jpeg)

ahora creo que si me meti desde github

**Comment by adsotoh** [comment]
@danapineiro, tienes que escribir el código y de ahí ejecutar las pruebas. Es por eso el error.
