### ISSUE TITLE
Información sobre inscripciones cerradas 

### ISSUE THREAD

**Issue by JulianaFacciolla** [Laboratoria/tech-support#66]
**Describe el problema**
En la landing https://bootcamp.laboratoria.la/es/web-dev sale que los bootcamps están con las inscripciones cerradas en las casillas de fechas y horário. En ADMIN las fechas de Admission End están correctas.

DEV009 - maio - Admission End 07/05
DEV010 - junho - Admission End 21/05

**Comportamiento esperado**
Debería aparecer Abierto

**Screenshots**
![Screen Shot 2023-04-27 at 11 52 42](https://user-images.githubusercontent.com/62949565/234912990-a77e8543-1750-46b8-aa4e-2b0afe5d7a9c.png)

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://admin.laboratoria.la/bootcamp/cohorts`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by lupomontero** [comment]
Esto ya está resuelto en producción. Gracias por reportar @JulianaFacciolla 💪
