### ISSUE TITLE
me aparece un error y no se como solucionar

### ISSUE THREAD

**Issue by paokaterine95** [Laboratoria/tech-support#67]
etiquetas <img> deberían tener atributos src y alt esperados

expected 'https://images.unsplash.com/photo-148…' to equal 'https://images.unsplash.com/photo-148…'

yo hice esto
<figure>
  <img 
  alt="Figure 1" 
  width="160" 
  src=" https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80"/>
  <figcaption>Figure 1</figcaption>
</figure>

**Comment by adsotoh** [comment]
@ib-frida

**Comment by Esther12233** [comment]
Hola, yo tengo el mismo problema, disculpa, te dieron una solución

**Comment by ib-frida** [comment]
¡Hola! 

Te compartimos este [link](https://laboratoria-1.gitbook.io/recursos-para-el-pre-trabajo?utm_source=gitbook&utm_medium=front&utm_campaign=admissions_latam&utm_content=resources_dev) donde encontrarás más información que te ayudará a resolver los ejercicios de código del Pre-Trabajo.

Por favor escríbenos nuevamente si tienes alguna otra duda.

¡Gracias!
