### ISSUE TITLE
horarios y nuevas admisiones

### ISSUE THREAD

**Issue by cotimendez** [Laboratoria/tech-support#68]
Hola 
Los horarios para Chile siempre son de 10 a 14?
Habrán nuevas admisiones en desde septiembre.

gracias

**Comment by adsotoh** [comment]
@ib-frida, ¿podrías responder a la postulante? Gracias.

**Comment by ib-frida** [comment]
¡Hola! Depende de la convocatoria, pero suele ser ese en Chile
