### ISSUE TITLE
URL name entity expected got none.

### ISSUE THREAD

**Issue by LessCGO** [Laboratoria/tech-support#69]
Estoy realizando el reto para postular al bootcamp de desarrollo web, y hay un error que me marca cuando coloco el URL para el atributo href y es el siguiente "Entity expected got none" y en el resultado de la prueba me aparece  lo siguiente expected '' to equal 'https://images.unsplash.com/photo-151…'

Este es el códgio que coloque, el error me lo marca cuando colocó el URL.
<figure>
      <img alt="Figure 1" width="160" href="https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80"/>
      <figcaption>Figure 1</figcaption>
</figure>

Agradezco la ayuda!

![Error](https://user-images.githubusercontent.com/132650172/236640615-954d8e4d-f032-4a67-aec8-8cd8a849741b.png)
![test ](https://user-images.githubusercontent.com/132650172/236640667-56de5865-c992-47d7-94e1-2fdd51467570.png)

**Location**: `https://bootcamp.laboratoria.la/es/account`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
@ib-frida

**Comment by Esther12233** [comment]
Hola, yo tengo el mismo problema, disculpa, te dieron una solución

**Comment by LessCGO** [comment]
> Hola, yo tengo el mismo problema, disculpa, te dieron una solución

Hola Esther, 
El error de name entity expected va seguir apareciendo pero aún asi puedes pasar las pruebas del reto, en realizad lo que yo tenía que solucionar era el error de la segunda imagen  **"etiquetas <img> deberían tener atributos src y alt esperados"**, lo que hice para corregir ese error fue cambiar el atributo con el que colocaba el URL de la imagen lo cambie de href="https://....." a src="https://... (esto es porque en los elementos de imagen para los URL no se utiliza href si no src). 

Te incluyo ejemplo de como quedo mi código:

<figure> <img alt="Figure 2" width="160" **src**="https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80"/> <figcaption>Figure 2</figcaption> </figure>


Ojala puedas solucionarlo, saludos.

**Comment by ib-frida** [comment]
¡Hola! 

Te compartimos este [link](https://laboratoria-1.gitbook.io/recursos-para-el-pre-trabajo?utm_source=gitbook&utm_medium=front&utm_campaign=admissions_latam&utm_content=resources_dev) donde encontrarás más información que te ayudará a resolver los ejercicios de código del Pre-Trabajo.

Por favor escríbenos nuevamente si tienes alguna otra duda.

¡Gracias!

**Comment by Esther12233** [comment]
Hola, buenas tardes, yo coloque de modo correcto las URLS en scr= sigo con el mismo problemas y no se como resolverlo, cheque los ejemplos pero yo no estoy mal,  no se que más hacer @ib-frida, @adsotoh 
![problemasURL1](https://github.com/Laboratoria/tech-support/assets/133852598/1da97add-9c8a-44c8-91dd-5176afe4ab7f)
