### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by Esther12233** [Laboratoria/tech-support#70]
Cuando estas en hacer un portafolio.
Cuando estas en la tercera parte las URL NO SIRVEN, marca error y no puedo avanzar, ya provee de todo y nada

**Comment by Esther12233** [comment]
![problemasURL1](https://github.com/Laboratoria/tech-support/assets/133852598/6342586f-9126-4aab-be9c-fcf6bcf850d5)

**Comment by Esther12233** [comment]
![URL2](https://github.com/Laboratoria/tech-support/assets/133852598/df7b6389-2c34-4c4c-9d4f-5565da3ae0cc)

**Comment by Esther12233** [comment]
no puedo avanzar por que no me deja enviarlo hasta hacerlo de una manera correcta
![URL4](https://github.com/Laboratoria/tech-support/assets/133852598/1ff846e3-bd8e-4186-a152-01bfa7d781bd)

**Comment by Esther12233** [comment]
@ib-frida , @adsotoh

**Comment by ib-frida** [comment]
¡Hola Esther! Los errores son problemas que tuviste en tu código que necesitan modificación. Como mencionas, tienes que hacer la postulación correctamente para poder enviarla de forma efectiva. 

Te compartimos este [link](https://laboratoria-1.gitbook.io/recursos-para-el-pre-trabajo?utm_source=gitbook&utm_medium=front&utm_campaign=admissions_latam&utm_content=resources_dev) donde encontrarás más información que te ayudará a resolver los ejercicios de código del Pre-Trabajo.

Por favor escríbenos nuevamente si tienes alguna otra duda.

¡Gracias!
