### ISSUE TITLE
[Bug] Reemplaza este texto con el título

### ISSUE THREAD

**Issue by SharomBromberg** [Laboratoria/tech-support#72]
**Describe el problema**
presenté la prueba y la pagina no carga, se queda totalmente en blanco, ni borrando datos de navegación recarga
**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a '...'
2. Hacer click en '....'
3. Hacer scroll hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Descripción clara y concisa de qué esperabas que ocurriera, que cargara la pagina, o que me llevara a otra prueba..

**Screenshots**
![image](https://github.com/Laboratoria/tech-support/assets/123013165/f76280b0-2069-48c8-b9a3-a3cabcbbfb65)

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/account`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @SharomBromberg ¿Podrías darnos más contexto al respecto para saber en que momento ocurrió este error? por ejemplo, ¿Estabas enviándo la postulación? o ¿O estabas testeando algún reto?

**Comment by SharomBromberg** [comment]
Hola, ya había hecho el código, presioné el único botón que me salía, si no
estoy mal solo salía el de testear y se fue a la página en blanco y no
volvió a cargar nada

**Comment by adolivaresl** [comment]
que reto estabas realizando?

**Comment by SharomBromberg** [comment]
El primero un portafolio en html

**Comment by SharomBromberg** [comment]
sigo atenta a la respuesta, ya que queda poco tiempo

**Comment by adolivaresl** [comment]
Hola Sharom, quisiera pedirte un par de datos más para poder reproducir el error:

1. ¿Puedes darme el paso a paso de lo que hiciste en la página? y asi intentaremos reproducir el error.
2. ¿Puedes darme más información sobre el navegador que estas utilizando para interactuar con la página?
3. ¿Podrías decirme si la sección de perfil o donde se ven los retos te muestra error también? o ¿es solo en la parte de portafolio?

**Comment by SharomBromberg** [comment]
Hice el codigo, le di al boton de abajo, que era testear o enviar, no
recuerdo bien, y se fue a una pagina en blanco, el perfil funciona, pero
cuando selecciono la parte de retos, me manda a una pagina en blanco, si le
doy regresar sigue en blanco y me toca cerrarla para ir de nuevo a mi
perfil, pero no me deja avanzar.
Estoy utilizando Chrome

**Comment by SharomBromberg** [comment]
ya probé con otros navegadores y no me deja avanzar en nada

**Comment by adolivaresl** [comment]
Gracias Sharom por toda la información que nos has entregado, estamos trabajando en tu caso para solucionarlo!

**Comment by adolivaresl** [comment]
Hola @SharomBromberg de momento estamos investigando este error más a profundidad, pero  hemos encontrado un solución momentánea para que puedas seguir avanzando en tu postulación, esta solución fue la de resetear tu ejercicio del reto de portafolio, por lo tanto deberías poder ver nuevamente la página de los retos y volver a ver su contenido. Por favor, avísanos si vuelves a tener este problema.
De antemano agradecemos que nos hayas reportado esto, y estaremos atentos a lo que nos puedas comentar.

**Comment by SharomBromberg** [comment]
volvió a suceder, cuando di click en ejecutar prueba

**Comment by SharomBromberg** [comment]
[image: image.png]

**Comment by adolivaresl** [comment]
Hola @SharomBromberg logramos identificar el error que reportaste y desplegamos un arreglo que lo corrige, eso si nuevamente tuvimos que borrar la data corrupta que generaba este error en tu reto de portafolio ( lo sentimos por eso) por lo tanto nuevamente te pedimos que vuelvas a desarrollar tu reto para seguir avanzando en tu postulación, pero en esta ocación esperamos que no vuelva a sucederte el mismo problema.
Muchas gracias por tu tiempo y paciencia, quedamos atentos.
Buen viernes.

**Comment by entelequiadivina** [comment]
Hola, ¿tuviste solución a este bug en la página? Porque estoy teniendo el mismo problema

**Comment by SharomBromberg** [comment]
Pues, al refrescar la pagina me dejó avanzar al fin, puedes intentar
haciendo eso

**Comment by SharomBromberg** [comment]
Ya había enviado la postulación, me toca hacerlo de nuevo? 😰

**Comment by adolivaresl** [comment]
Hola @SharomBromberg confirmamos que tu postulación llegó sin problemas, no es necesario que debas realizarla nuevamente.
