### ISSUE TITLE
Soy de Perú y no me permite acceder

### ISSUE THREAD

**Issue by Treialex** [Laboratoria/tech-support#73]
Hola buenas tardes, agradezco por la oportunidad de acceder al Bootcamp y a esta gran oportunidad. Sin embargo al registrarme, me dice que no está el país Perú para Laboratoria, y luego me dice que sí,pero al yo intentar acceder desde Perú no me lo permite. Por favor, realmente quisiera participar en el programa y poder aprender junto con ustedes, de igual forma, valoro y apoyo mucha esta iniciativa, que sigan siendo bendencidas y sigan surgiendo! Se lo merecen. Feliz tarde, quedo a la espera de su respuesta.

**Comment by adsotoh** [comment]
Hola, @Treialex. En este momento, deberías poder postular a los bootcamps en los cuales aparece la bandera de Perú. Ahora, son los del 14 de agosto y 11 de septiembre: 
<img width="512" alt="Captura de pantalla 2023-06-20 a la(s) 12 42 07" src="https://github.com/Laboratoria/tech-support/assets/122818667/1dbdd578-ddfb-4f67-ac6a-02de62458f34">
