### ISSUE TITLE
Portafolio

### ISSUE THREAD

**Issue by KneRodri** [Laboratoria/tech-support#74]
Hola, espero se encuentren bien. Estoy realizando la postulación y me encuentro resolviendo el tema de Portafolios. Me da error en la parte de figure, he revisado y creo tenerlo bien, me pueden ayudar por favor.
![image](https://github.com/Laboratoria/tech-support/assets/134166821/54a3f218-57ea-4301-b08f-3dbe27097e94)
![image](https://github.com/Laboratoria/tech-support/assets/134166821/77bd1f2f-7596-4ec6-a93c-eb643cbdf0d0)

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/applications/204663/challenges/portfolio`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by ib-frida** [comment]
¡Hola! 

Te compartimos este [link](https://laboratoria-1.gitbook.io/recursos-para-el-pre-trabajo?utm_source=gitbook&utm_medium=front&utm_campaign=admissions_latam&utm_content=resources_dev) donde encontrarás más información que te ayudará a resolver los ejercicios de código del Pre-Trabajo.

Por favor escríbenos nuevamente si tienes alguna otra duda.

¡Gracias!
