### ISSUE TITLE
Problemas a la hora de realizar el reto número 1

### ISSUE THREAD

**Issue by entelequiadivina** [Laboratoria/tech-support#75]
Hola, a la hora de tratar de realizar el reto 1 no puedo ejecutar las pruebas, la pantalla queda en blanco.

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a '...'
2. Hacer click en '....'
3. Hacer scroll hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Descripción clara y concisa de qué esperabas que ocurriera.

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/auth/signin`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
**Navigator Language**: `es-MX`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Hola, @entelequiadivina, para poder apoyarte, necesitamos que compartas la siguiente información:

**Qué reto es**

**Para reproducirlo**
Pasos para reproducir el problema:

**Ejemplo:**

Ir a '...'
Hacer click en '....'
Hacer scroll hacia abajo hasta '....'
Ver error

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.

**Comment by adsotoh** [comment]
Issue cerrado por falta de respuesta de la postulante.
