### ISSUE TITLE
No recarga

### ISSUE THREAD

**Issue by NatieKonstanze** [Laboratoria/tech-support#76]
**Describe el problema**
La pantalla de laboratoria al hacer el desafío de desarrollo web no recarga a pesar de tener buena conexión a internet.

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a '...'
2. Hacer click en '....'
3. Hacer scroll hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Descripción clara y concisa de qué esperabas que ocurriera.

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/applications/200561/challenges/coin-convert`
**User Agent**: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Mobile Safari/537.36`
**Navigator Language**: `es-US`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Hola, @NatieKonstanze, para poder apoyarte, necesitamos que compartas la siguiente información:

**Para reproducirlo**
Pasos para reproducir el problema:

Ejemplo: 

Ir a '...'
Hacer click en '....'
Hacer scroll hacia abajo hasta '....'
Ver error

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.

**Comment by adsotoh** [comment]
Issue cerrado por falta de respuesta de la postulante.
