### ISSUE TITLE
ERROR: etiquetas <img> deberían tener atributos src y alt esperados. 

### ISSUE THREAD

**Issue by ymarianarojas** [Laboratoria/tech-support#77]
**Estoy realizando la siguiente tarea y me dice que las etiquetas <img> deberían tener atributos src y alt esperados.** 

Después del <aside> debe venir una etiqueta <main>, con seis hijitos: un <h2> con el texto Work, seguido de cinco etiquetas <figure>.

Cada una de las etiquetas <figure> debe contener una imagen (<img>), y una etiqueta <figcaption>. Por ejemplo:

<figure>
  <img
    alt="Figure 1"
    width="160"
    src=""
  />
  <figcaption>
    Figure 1
  </figcaption>
</figure>
En cada imágen tendremos que cambiar los atributos alt y src, así como el número en el texto de <figcaption> (Figure 1, Figure 2, etc).

Aquí tenemos el detalle con los textos a usar en el atributo alt y <figcaption> así como las URLs de las imágenes (a usar en atributo href).

Figure 1: https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80
Figure 2: https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80
Figure 3: https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80
Figure 4: https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80
Figure 5: https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80

**HE ESCRITO LO SIGUIENTE:** 

  <figure>
  <img
    alt="Figure 1"
    src="https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-"
  />
  <figcaption>Figure 1</figcaption>
  </figure>
    
  <figure>
  <img
    alt="Figure 2"
    src="https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?ixlib=rb-"
  />
  <figcaption>Figure 2</figcaption>
  </figure>
    
  <figure>
  <img
    alt="Figure 3"
    src="https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-"
  />
  <figcaption>Figure 3</figcaption>
  </figure>

  <figure>
  <img
    alt="Figure 4"
    src="https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?ixlib=rb-"
  />
  <figcaption>Figure 4</figcaption>
  </figure>
    
  <figure>
  <img
    alt="Figure 5"
    src="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-"
  />
  <figcaption>Figure 5</figcaption>
  </figure>

**Comment by adsotoh** [comment]
Hola, @ymarianarojas. Disculpas por la demora en responder. Nos gustaría entender si esto que reportaste sigue siendo un problema. Gracias.

**Comment by ymarianarojas** [comment]
Esta resuelto. Gracias
