### ISSUE TITLE
No entiendo lo que requiere, podrían ser más específicos respecto a cómo quieren el código o lo que quiere que muestre

### ISSUE THREAD

**Issue by lapp0720** [Laboratoria/tech-support#78]
En este espacio puedes agregar el contexto necesario: texto, screenshots, etc.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/auth/signin?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
**Navigator Language**: `es-US`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Hola, @lapp0720 , necesitamos que seas más específica sobre lo que estás reportando, ya que la descripción no tiene información. Gracias.

**Comment by adsotoh** [comment]
Issue cerrado por falta de respuesta de la postulante.
