### ISSUE TITLE
Consulta postulación de agosto

### ISSUE THREAD

**Issue by mvejarp** [Laboratoria/tech-support#79]
Buenas tardes, postulé a laboratoria para entrar en marzo, tuve la entrevista pero luego no llegó nada mas de información. Hace un tiempo entre a la plataforma y revisando pude cambiar la fecha de la convocatoria para agosto, tuve que hacer nuevamente las pruebas, me llegaron los correos para participar de las charlas informativas y etc. Resulta que hoy ingreso nuevamente para verificar y no me aparece nada de la postulación ya realizada para agosto, si no que la pagina me entrega el formulario para postular desde 0 con fecha ya para septiembre. No se si esto es un error o alguien me pueda orientar por favor, gracias.

el correo de postulación es marcelavejar@hotmail.com

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/?utm_source=laboratoria_web&utm_medium=header&utm_campaign=header_laboratoria-web`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
**Navigator Language**: `es-US`
**Selected Language**: `es`

**Comment by ib-frida** [comment]
¡Hola Marcela! Tenemos tus datos con tu pre-trabajo hecho, no te preocupes, como tuvimos un aplazo de nuestra fecha límite, en tu plataforma te aparecerá de esa manera, pero tus avances los tenemos registrados internamente.

Dentro de esta semana llegarán los resultados! Mucha suerte
