### ISSUE TITLE
[Question] "as tags <img> devem ter atributos src e alt esperados"

### ISSUE THREAD

**Issue by cleanyteixeira** [Laboratoria/tech-support#82]
Não estou conseguindo resolver esse problema. 
os atributos estão separados, mesmo assim não consigo completar a questão.

**Alerta**
Lembre-se que este repositório é público, todos os problemas e conversas
relacionados são públicos e visíveis para todos.
Se você precisar compartilhar informações conosco em particular, NÃO faça isso por meio deste repositório,
Entraremos em contato com você para poder fornecer suporte por meio de um canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/pt/account`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`
**Navigator Language**: `pt-BR`
**Selected Language**: `pt`

**Comment by JulianaFacciolla** [comment]
Olá! Por favor encaminhar a sua dúvida para selecao@laboratoria.la
Obrigada!
