### ISSUE TITLE
[Bug] En el desplegabe de institución universitaria no encuentro la mia y no me deja completar mi inscripción.

### ISSUE THREAD

**Issue by mariamedina19** [Laboratoria/tech-support#83]
**Describe el problema**
Descripción clara y concisa de cuál es el problema.

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a '...'
2. Hacer click en '....'
3. Hacer scroll hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Descripción clara y concisa de qué esperabas que ocurriera.

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
**Navigator Language**: `es-CO`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Hola, @mariamedina19, ¿cuál es tu universidad?

**Comment by mariamedina19** [comment]
Mi universidad es la Cooperativa de Colombia 🥺

**Comment by rocioalberdi** [comment]
Hola @mariamedina19 en caso no encuentres tu universidad puedes seleccionar la opción "otro", me cuentas si te funciona :)
