### ISSUE TITLE
[Pregunta] ¡como ubico mi universidad en los formularios de inscripción de los bootcamps

### ISSUE THREAD

**Issue by mariamedina19** [Laboratoria/tech-support#84]
En este espacio puedes agregar el contexto necesario: texto, screenshots, etc.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
**Navigator Language**: `es-CO`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Issue cerrado en favor de: https://github.com/Laboratoria/tech-support/issues/83
