### ISSUE TITLE
Duda respecto a desafío "Cuenta de restaurante"

### ISSUE THREAD

**Issue by carolina-aburto** [Laboratoria/tech-support#85]
Hola!

He estado trabajando en el desafío "cuenta de restaurante" y aún no logro finalizarlo con éxito. Quisiera pedirles ayuda y/o orientación de en donde podría estar cometiendo el error. Les adjunto mi avance, quedo atenta a su feedback.

const restaurantBill = (bill) => {
  const tax = bill*0.1;
  const total= bill + tax;
  const montoPorPersona = total/5;
  return `$${montoPorPersona}`;
};

const montoPorPersona = restaurantBill(50);
console.log(`${montoPorPersona}`);

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/account`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Hola, @carolina-aburto. Te compartimos un recurso que podría funcionarte a resolver el reto: https://laboratoria-1.gitbook.io/recursos-para-el-pre-trabajo/cuenta-de-restaurante
