### ISSUE TITLE
[Bug] Reemplaza este texto con el título

### ISSUE THREAD

**Issue by renatanaranjo** [Laboratoria/tech-support#86]
**Describe el problema**
Al intentar enviar el ejercicio, me marca dos errores en las etiquetas <a> que van con los enlaces a el mail, y a una búsqueda en google. He intentado resolverlo pero lo he comparado con ejemplos, o escribiéndolo de diferentes formas, y me sigue marcando el error, y es el único que no he podido resolver. Quisiera saber cómo puedo seguir para poder enviar el ejercicio.

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el  #problema.
/

-   #@``

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/auth/signin`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
**Navigator Language**: `es-ES`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Hola, @renatanaranjo. Disculpas por la demora en la respuesta a tu duda. Para entender mejor, ¿de cuál reto hablas y de postulación a qué Bootcamp?

**Comment by adsotoh** [comment]
Cerramos el issue por falta de respuesta. @renatanaranjo, si el problema persiste, es necesario que hablas un nuevo issue a través de la plataforma.
