### ISSUE TITLE
Mensaje

### ISSUE THREAD

**Issue by macaave** [Laboratoria/tech-support#88]
Necesito comunicarme de manera privada.
Saludos

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/auth/signin`
**User Agent**: `Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/115.0.5790.160 Mobile/15E148 Safari/604.1`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Hola, @macaave . Puedes enviar un correo a postula@laboratoria.la. Saludos.
