### ISSUE TITLE
Dúvida ao bootcamp

### ISSUE THREAD

**Issue by LeticiaMile** [Laboratoria/tech-support#89]
Neste espaço você pode adicionar o contexto necessário: texto, screenshots, etc.

Bom dia, boa tarde e boa noite!
Seria em relação a um desafio do bootcamp, eu fiz essa parte exatamente como foi pedido, mas mesmo assim diz  que está com erro:

<figure>
          <img
          alt="Figure 1"
          width="160"
          src="https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80"
            />
       <figcaption>
          Figure 1
        </figcaption>
      </figure>
      <figure>
        <img
        alt="Figure 2"
        width="160"
        src="https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80"
        />
        <figcaption>
         Figure 2
        </figcaption>
      </figure>
      <figure>
        <img
        alt="Figure 3"
        width="160"
        src="https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80"
        />
        <figcaption>
        Figure 3
        </figcaption>
      </figure>
        <figure>
          <img
        alt="Figure 4"
        width="160"
        src="https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80"
        />
        <figcaption>
        Figure 4
        </figcaption>
        </figure>
        <figure>
          <img
        alt="Figure 5"
        width="160"
        src="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
        />
        <figcaption>
        Figure 5
        </figcaption>
        </figure> 
        
ERRO: tags <figcaption> devem ter o texto esperado

expected '\n Figure 1\n ' to equal 'Figure 1'

(Não entendi o erro, poderia verificar?)
Desde já, agradeço.

## Entorno

**Location**: `https://bootcamp.laboratoria.la/pt/auth/signin`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0`
**Navigator Language**: `pt-BR`
**Selected Language**: `pt`

**Comment by JulianaFacciolla** [comment]
Olá! Por favor encaminhar a sua dúvida para selecao@laboratoria.la
Obrigada!
