### ISSUE TITLE
Padronización nombre programa

### ISSUE THREAD

**Issue by JulianaFacciolla** [Laboratoria/tech-support#9]
**La mejora que quieres proponer hace relación a un problema?**
Creo que deberíamos usar el nombre del bootcamp siempre en ES o PT. = Bootcamp de Desarrollo Web

**Describe la solución que te gustaría**
En la pregunta de edad, cuando es menor de edad, sale "Bootcamp Web Dev" en el mensaje" 
![Screen Shot 2023-02-24 at 15 40 39](https://user-images.githubusercontent.com/62949565/221265804-7b5405c6-4dc7-49e8-a8f4-20d1df281b95.png)

En el aviso que es menor de edad, usamos "Bootcamp Web Dev"

**¿Qué alternativas has considerado?**
Descripción clara y concisa de otras soluciones alternativas que hayas
considerado.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://laboratoria-bootcamp-next.web.app/es/auth/signup?r=/es/apply?programId=1`
**User Agent**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36`
**Navigator Language**: `en-US`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
@rocioalberdi , ¿priorizamos este cambio que sugiere Ju?

**Comment by rocioalberdi** [comment]
No lo priorizaría ahora. Sí estoy de acuerdo con que debemos dejarlo igual, pero podemos hacerlo más adelante

**Comment by adsotoh** [comment]
Cerrado en favor de: https://github.com/Laboratoria/bootcamp.laboratoria.la/issues/193
