### ISSUE TITLE
[Bug] Reemplaza este texto con el título

### ISSUE THREAD

**Issue by MrMidnight02** [Laboratoria/tech-support#90]
**Describe el problema**
Error de carga de reto de ingreso ¨Cuenta de restaurante¨
**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a 'bootcamp de desarrollo web'
2. Hacer click en 'cuenta de restaurante'
3. Hacer scroll hacia abajo hasta 'Solucion - ejecutar pruebas.'
4. Ver error

**Comportamiento esperado**
El codigo ingresado deberia cumplir con los requerimientos solicitados ya que se han proporcionado distintos codigos que satisfacen las indicaciones de lo que el programa debe ser capaz de ejecutar

**Screenshots**
![Captura de pantalla 2023-08-20 000109](https://github.com/Laboratoria/tech-support/assets/142710621/c06dacb0-140e-45e5-b5b4-79061f78d145)

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/account`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203`
**Navigator Language**: `es`
**Selected Language**: `es`

**Comment by adsotoh** [comment]
Hola, @MrMidnight02, te compartimos un recurso que podría ayudarte a resolver el reto: https://laboratoria-1.gitbook.io/recursos-para-el-pre-trabajo/cuenta-de-restaurante
