### ISSUE TITLE
Não consigo concluir os exercícios 

### ISSUE THREAD

**Issue by Melaraujoco** [Laboratoria/tech-support#91]
Não estou conseguindo concluir os exercícios, o sistema não deixa eu refazer, lá aparece que eu já fiz três de três e não me permite refazer, e eu não consigo enviar o teste para vocês, estou recebendo bastante mensagem pedindo para eu finalizar mais não estou conseguindo vocês pode me ajudar

**Comment by JulianaFacciolla** [comment]
Olá, @Melaraujoco. Você pode entrar em contato pelo e-mail selecao@laboratoria.la
