### ISSUE TITLE
[Bug] Reemplaza este texto con el título

### ISSUE THREAD

**Issue by merigoom** [Laboratoria/tech-support#92]
**Describe el problema**
Descripción clara y concisa de cuál es el problema.
En dar click en  nacionalidad no aparecen países latinos  entre ellos no da la opción de elegir México.

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a '...'
2. Hacer click en '....'
3. Hacer scroll hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Descripción clara y concisa de qué esperabas que ocurriera.

**Screenshots**
Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.
![image](https://github.com/Laboratoria/tech-support/assets/141360348/1ae9ebdf-ae8f-4702-a61f-0be657c71b6f)

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/data?utm_source=mailing+&utm_medium=boton_postula&utm_campaign=leads-2023&utm_id=mailing+bootcamp+analisis+de+datos+`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
**Navigator Language**: `es-MX`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @merigoom podrías indicarme a qué programa del bootcamp (Desarrollo web, Ux Design o Analista de datos) estas intentando postular? 

También puede pasar que en esa sección de ¿Cuál es tu nacionalidad?,  si buscas con la flecha para abrir el listado de opciones solo te muestra unas cuantas ya que el listado es enorme, lo que debes hacer es tu misma escribir "mex" y te va a aparecer la opción de "MX/México" 

Cuéntame si lograste solucionarlo. ten un buen viernes.

**Comment by merigoom** [comment]
Hola, estoy postulando a análisis de datos muchas gracias por su respuesta ya pude resolverlo tenga un buen día. Enviado desde Correo para Windows De: Domi OlivaresEnviado: viernes, 1 de septiembre de 2023 07:05 a. m.Para: Laboratoria/tech-supportCC: Maria Fernanda Gomez Miranda; MentionAsunto: Re: [Laboratoria/tech-support] [Bug] Reemplaza este texto con el título (Issue #92) Hola @merigoom podrías indicarme a qué programa del bootcamp (Desarrollo web, Ux Design o Analista de datos) estas intentando postular?También puede pasar que en esa sección de ¿Cuál es tu nacionalidad?, si buscas con la flecha para abrir el listado de opciones solo te muestra unas cuantas ya que el listado es enorme, lo que debes hacer es tu misma escribir "mex" y te va a aparecer la opción de "MX/México"Cuéntame si lograste solucionarlo. ten un buen viernes.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by adolivaresl** [comment]
Súper, muchas gracias por contactarte con nosotros. Cierro este issue como resuelto.
