### ISSUE TITLE
[Bug] Reemplaza este texto con el título

### ISSUE THREAD

**Issue by kiod3** [Laboratoria/tech-support#93]
**Describe el problema**
No puedo acceder a la copia del dataset "Teste spreadsheet" del Reto para el Bootcamp Data Analytics

**Para reproducirlo**
Pasos para reproducir el problema:
1. Ir a 'Iniciar reto'
2. Hacer click en 'Dataset'
3. Hacer click en 'Hacer una copia'
4. Ver error

**Comportamiento esperado**
Se tenía que abrir google shell para poder hacer una copia al dataset y empezar el reto

**Screenshots**
![image](https://github.com/Laboratoria/tech-support/assets/103378496/d2b44311-e6e3-4865-8879-d5665d418cc1)

Si es posible, agrega screenshots (capturas de pantalla) para ayudar a entender
el problema.

**Contexto adicional**
Agrega cualquier otra cosa que pueda ayudar a entender el contexto en el que
ocurre el problema.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es/auth/signin?r=/es/apply?programId=4`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 OPR/101.0.0.0`
**Navigator Language**: `es-419`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @kiod3 podrías indicarme si ya lograste copiar el dataset? si aún no has podido, por favor indícame el paso a paso de que hiciste para llegar al error  y si iniciaste con tu cuenta de Google( Gmail)?

**Comment by kiod3** [comment]
Buenas tardes, ya pude acceder al dataset

Muchas gracias

**Comment by adolivaresl** [comment]
Que buena noticia!
Muchas gracias por comunicarte con nosotros y reportarnos tu problema, 
esperamos tenga una buena tarde.

**Comment by adolivaresl** [comment]
Procedo a cerrar este issue.
