### ISSUE TITLE
Sobre o processo seletivo, Conversor de Moeda, nesta fase meu codigo está correto, porem está dando erro, executando ,por favor tem como olhar? não está reconhecendo a função coinConvert como uma função válida.

### ISSUE THREAD

**Issue by aanneee** [Laboratoria/tech-support#94]
const coinConvert = (dollars) => {
  // Taxas de câmbio
  const taxaCambioSoles = 3.25;   // Taxa de câmbio para soles peruanos
  const taxaCambioPesosMexicanos = 18;  // Taxa de câmbio para pesos mexicanos
  const taxaCambioPesosChilenos = 660;   // Taxa de câmbio para pesos chilenos

  // Calcula o valor equivalente em cada moeda
  const soles = dollars * taxaCambioSoles;
  const pesosMexicanos = dollars * taxaCambioPesosMexicanos;
  const pesosChilenos = dollars * taxaCambioPesosChilenos;

  return [soles, pesosMexicanos, pesosChilenos];
};

// Exemplos de uso da função
const resultado1 = coinConvert(50);
const resultado2 = coinConvert(100);
const resultado3 = coinConvert(85);

console.log(resultado1); // Deve imprimir [162.5, 900, 33000]
console.log(resultado2); // Deve imprimir [325, 1800, 66000]
console.log(resultado3); // Deve imprimir [276.25, 1350, 49500]

**Comment by mfdebian** [comment]
Olá @aanneee, acho que seu código corresponde a uma versão antiga do desafio, efetivamente, seu código fica correto, mas probablemente você eliminou sem querer a última linha do código, que é nova e deve estar presente para que os testes passem
