### ISSUE TITLE
Olá novamente meu codigo está dando problema, por favor verificar

### ISSUE THREAD

**Issue by aanneee** [Laboratoria/tech-support#95]
const restaurantBill = (bill) => {
  const taxRate = 0.08; // Assuming a tax rate of 8%
  const tipPercentage = 0.15; // Assuming a tip of 15%

  const tax = bill * taxRate;
  const tip = bill * tipPercentage;
  const totalCost = bill + tax + tip;

  return `$${totalCost.toFixed(2)}`;
};

// Test cases
console.log(restaurantBill(11)); // Should return '$50'
console.log(restaurantBill(22)); // Should return '$100'
console.log(restaurantBill(18.7)); // Should return '$85'

**Comment by adolivaresl** [comment]
Olá @aanneee , muito obrigado por entrar em contato conosco. Você pode nos fornecer mais contexto sobre o que não está funcionando? Por exemplo, você poderia nos enviar uma captura de tela do editor de texto do desafio e também do que os testes dizem. Lembre-se de que os testes ajudam a entender o que se espera que o seu código faça.

**Comment by JulianaFacciolla** [comment]
Olá, @aanneee. Você pode entrar em contato pelo e-mail selecao@laboratoria.la.
