### ISSUE TITLE
[Pregunta] Reemplaza este texto con el título

### ISSUE THREAD

**Issue by Laurenj10** [Laboratoria/tech-support#96]
¿Dónde puedo encontrar información detallada sobre el pensum del bootcamp que ofrece Laboratoria? Estoy interesada en conocer en profundidad los temas y habilidades que se enseñan durante el programa.

**Alerta**
Recuerda que este repositorio es público, todos los issues y conversaciones 
relacionadas son públicas y visibles a todo el mundo.
Si necesitas compartirnos información de forma privada, NO lo hagas a través de este repo, 
nos pondremos en contacto para poder dar soporte a través de un canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/es?utm_source=laboratoria_web&utm_campaign=footer_laboratoria-web&utm_medium=footer&_ga=2.98090911.1857652918.1694288048-1556364496.1694285982`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.76`
**Navigator Language**: `es`
**Selected Language**: `es`

**Comment by adolivaresl** [comment]
Hola @Laurenj10 aquí puedes encontrar información sobre los proyectos en los que trabajan las estudiantes y algunas lecturas sugeridas: https://curriculum.laboratoria.la/es/
Gracias por contactarte con nosotros, que tengas buen día.
