### ISSUE TITLE
tengo el problema con la etiqueta <img src="">

### ISSUE THREAD

**Issue by Villensa** [Laboratoria/tech-support#97]
feliz tarde me podrían orientar ya que en vscode realice, el código y me corre bien y cuando, pego el código en donde dice solución me sale 21 líneas de código buenas y una mala en la cual hace referencia a la imagen 

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jane Doe</title>
</head>
<body>
    <header>
        <h1>Jane Doe</h1>
    </header>
    <aside>
        <ul>
            <li><a href="mailto:jane@doe.com">Contact</a></li>
            <li><a href="https://www.google.com/search?q=jane+doe">About</a></li>
        </ul>
    </aside>
    <main>
      <h2>Work</h2>
      <figure>
        <img
          alt="Figure 1"
          width="160"
          src="https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80"
        />
        <figcaption>
          Figure 1
        </figcaption>
      </figure>
      <figure>
        <img
          alt="Figure 2"
          width="160"
          src="https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80"
        />
        <figcaption>
          Figure 2
        </figcaption>
      </figure>
      <figure>
        <img
          alt="Figure 3"
          width="160"
          src="https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80"
        />
        <figcaption>
          Figure 3
        </figcaption>
      </figure>
      <figure>
        <img
          alt="Figure 4"
          width="160"
          src="https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80"
        />
        <figcaption>
          Figure 4
        </figcaption>
      </figure>
      <figure>
        <img
          alt="Figure 5"
          width="160"
          src="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
        />
        <figcaption>
          Figure 5
        </figcaption>
      </figure>
      
    </main>
    <footer>Jane Doe &copy; 2023</footer>
</body>
</html>`

![image](https://github.com/Laboratoria/tech-support/assets/144841454/6bbfb152-fc72-491e-8110-877b11ef31f5)

**Comment by adolivaresl** [comment]
Hola @Villensa, espero te encuentres bien, gracias por contactarte con nosotros. Deberías revisar la información que te dá el test, el test te dice que es lo que se espera que suceda y no está sucediendo ( en el caso de la línea que te sale como errónea)
