### ISSUE TITLE
cuenta restaurante

### ISSUE THREAD

**Issue by Villensa** [Laboratoria/tech-support#98]
Feliz noches tengo duda con el código de restaurante ya que no doy con el resultado, me gustaría que me contacten para que por favor me den una orientación, sobre mi ejercicio, ya que me estoy guiando por su plantilla y no logro dar con el resultado, ademas es mi primera vez trabajando con esto y no se si valla en la dirección correcta.
 `const restaurantBill = (bill) => {
const tax = bill*0.1;
const total= bill + tax;
const cuentaTotal = total/5;
return ("cuentaTotal")
};

const cuentaTotal = restaurantBill(50);
console.log("cuentaTotal 11 $")`

**Comment by adolivaresl** [comment]
Hola @Villensa, escríbenos a este correo: **postula@laboratoria.la** y con gusto te darán orientación sobre tu ejercicio.

**Comment by adsotoh** [comment]
@Villensa, cerraremos este issue. Si sigues teniendo problema, no dudes en escribir a [postula@laboratoria.la](mailto:postula@laboratoria.la). Gracias.
