### ISSUE TITLE
Execusão de testes com erro

### ISSUE THREAD

**Issue by LuB0ld** [Laboratoria/tech-support#99]
Todas as minhas tentativas de executar os testes, estão retornando com o mesmo resultado. Até mesmo se eu excluir todo o código e apertar para testar, o retorno é sempre o mesmo. Com isso, nunca sabarei se irei acertar o exercício 

Gostaria de verificar se existe alguma erro no código realmente, para que eu possa refazê-lo da maneira correta ou por fim se acertei ou não

Os prints do ocorrido:

![image](https://github.com/Laboratoria/tech-support/assets/145934087/a47145b4-6c0a-4f28-8cb0-019c97aecd5f)

![image](https://github.com/Laboratoria/tech-support/assets/145934087/547f219e-2ac5-4d29-95a2-2c6f9d9b559a)

**Contexto adicional**
Adicione qualquer outra coisa que possa ajudar a entender o contexto em que
o problema ocorre.

**Alerta**
Lembre-se que este repositório é público, todos os problemas e conversas
relacionados são públicos e visíveis para todos.
Se você precisar compartilhar informações conosco em particular, NÃO faça isso por meio deste repositório,
Entraremos em contato com você para poder fornecer suporte por meio de um canal privado.

***

## Entorno

**Location**: `https://bootcamp.laboratoria.la/pt/`
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 OPR/102.0.0.0`
**Navigator Language**: `pt-BR`
**Selected Language**: `pt`

**Comment by adolivaresl** [comment]
Hola @LuB0ld , obrigado por entrar em contato conosco. O erro que você está enfrentando ocorre devido à falta de uma linha de código necessária para que os testes possam avaliar o seu exercício. No final do seu código, você deve adicionar isso (que já estava no boilerplate do editor de texto) e, como vejo nas capturas de tela que você enviou, você já havia excluído esta linha, que faz referência a "module.exports". Deixo uma imagem de referência aqui embaixo. Espero que isso ajude você a resolver o seu problema. Tenha um bom dia.

![image](https://github.com/Laboratoria/tech-support/assets/32287138/2d7b3813-5b99-47ad-9f95-6fc564bc1129)

**Comment by LuB0ld** [comment]
> Hola @LuB0ld , obrigado por entrar em contato conosco. O erro que você está enfrentando ocorre devido à falta de uma linha de código necessária para que os testes possam avaliar o seu exercício. No final do seu código, você deve adicionar isso (que já estava no boilerplate do editor de texto) e, como vejo nas capturas de tela que você enviou, você já havia excluído esta linha, que faz referência a "module.exports". Deixo uma imagem de referência aqui embaixo. Espero que isso ajude você a resolver o seu problema. Tenha um bom dia.
> 
> ![image](https://user-images.githubusercontent.com/32287138/270376937-2d7b3813-5b99-47ad-9f95-6fc564bc1129.png)

![image](https://github.com/Laboratoria/tech-support/assets/145934087/17d87ed3-70b9-4e4c-92b2-4efd68f46dd9)


Deu super certo
MUITO OBRIGADA <3
